### ISSUE TITLE
关于bazel编译报错的问题

### ISSUE THREAD

**Issue by xiuechen** [Tencent/plato#101]
由于我的机器是无法连接外网的。因此在执行bazel build的时候会报错：

ERROR: An error occurred during the fetch of repository 'rules_cc':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip, https://github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip] to /home/work/.cache/bazel/_bazel_work/9980eccc9d4ccf98c57b95bc0965ab95/external/rules_cc/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip: connect timed out
ERROR: While resolving toolchains for target //plato/algo/bfs:bfs: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip, https://github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip] to /home/work/.cache/bazel/_bazel_work/9980eccc9d4ccf98c57b95bc0965ab95/external/rules_cc/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip: connect timed out

我尝试使用repository-cache来解决：（https://bazel.build/designs/2016/09/30/repository-cache.html ）
echo 'build --repository_cache=/path/to/cache' > /path/to/bazelrc
bazel --bazelrc=/path/to/bazelrc build

并且将0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip这个文件拷贝到/path/to/cache目录下，但是还是不行。

有人知道如何解决这个问题吗？怎么样让bazel去读取我本地下载的文件，而不是从http上去下载呢？

我知道bazel有一个方案是去WORKSPACE中设置：https://docs.bazel.build/versions/3.3.0/be/workspace.html#new_local_repository  但是问题是我看整个构建的过程，貌似0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip这种bazel自身依赖的包，都是从A-server.jar这个包里获取的，我尝试改了这个包内容里面获取该包的路径，直接bazel构建就会发现，然后报包被篡改，让我删除。

怎么解决啊，跪求方案。。

**Comment by ustcyu** [comment]
Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改脚本使用本地软件源。

**Comment by ustcyu** [comment]
Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。

**Comment by xiuechen** [comment]
> Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。

我这边不是在3rdtool阶段出错的，是在bazel编译阶段。

这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））

可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir

在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）

local_repository(
    name = "rules_cc",
    path = "/path/to/unzipdir",
)

重新编译就可以了。。

**Comment by zijinoier** [comment]
> > Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。
> 
> 我这边不是在3rdtool阶段出错的，是在bazel编译阶段。
> 
> 这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））
> 
> 可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir
> 
> 在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）
> 
> local_repository(
> name = "rules_cc",
> path = "/path/to/unzipdir",
> )
> 
> 重新编译就可以了。。

Thanks a lot.

**Comment by tuobashaoli** [comment]
thanks

**Comment by letianzhao** [comment]
> > Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。
> 
> 我这边不是在3rdtool阶段出错的，是在bazel编译阶段。
> 
> 这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））
> 
> 可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir
> 
> 在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）
> 
> local_repository(
> name = "rules_cc",
> path = "/path/to/unzipdir",
> )
> 
> 重新编译就可以了。。

您好，首先谢谢您的方法，很有效的解决了前几个依赖安装问题。
可是后面几个java环境的安装就不能简单的把压缩文件解压后添加workspace了，还是会报错 no such package
请问您有解决方法吗，谢谢。

**Comment by abasi20** [comment]
> > > Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。
> > 
> > 
> > 我这边不是在3rdtool阶段出错的，是在bazel编译阶段。
> > 这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））
> > 可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir
> > 在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）
> > local_repository(
> > name = "rules_cc",
> > path = "/path/to/unzipdir",
> > )
> > 重新编译就可以了。。
> 
> 您好，首先谢谢您的方法，很有效的解决了前几个依赖安装问题。 可是后面几个java环境的安装就不能简单的把压缩文件解压后添加workspace了，还是会报错 no such package 请问您有解决方法吗，谢谢。
我把test内容注释掉了，跳过此处编译，可以编译pagerank
这个问题解决了吗？ 这几个java的问题怎么解决

**Comment by freekevinCode** [comment]
> > > > Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。
> > > 
> > > 
> > > 我这边不是在3rdtool阶段出错的，是在bazel编译阶段。
> > > 这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））
> > > 可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir
> > > 在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）
> > > local_repository(
> > > name = "rules_cc",
> > > path = "/path/to/unzipdir",
> > > )
> > > 重新编译就可以了。。
> > 
> > 
> > 您好，首先谢谢您的方法，很有效的解决了前几个依赖安装问题。 可是后面几个java环境的安装就不能简单的把压缩文件解压后添加workspace了，还是会报错 no such package 请问您有解决方法吗，谢谢。
> > 我把test内容注释掉了，跳过此处编译，可以编译pagerank
> > 这个问题解决了吗？ 这几个java的问题怎么解决

我们采用的方法是 先在有外网的机器上 进行 bazel build  然后把cache目录中的external目录 直接拷贝出来 在你没有外网的机器上拷贝这个目录到相应位置即可

**Comment by letianzhao** [comment]
> > > > > Plato默认通过外网下载，无法连接外网的解决方案可询问bazel，或者尝试修改3rdtools.sh脚本使用本地软件源。
> > > > 
> > > > 
> > > > 我这边不是在3rdtool阶段出错的，是在bazel编译阶段。
> > > > 这个问题解决了，在这里说下解决方案，也给后面有类似经历的同学参考。（第一次用bazel蹚了很多坑：））
> > > > 可以先把报错的zip包下载下来，手工放到机器上，然后解压，假设解压后路径为/path/to/unzipdir
> > > > 在当前目录的WORKSPACE当中添加一条规则：（以我之前的问题为例，缺乏rules_cc依赖）
> > > > local_repository(
> > > > name = "rules_cc",
> > > > path = "/path/to/unzipdir",
> > > > )
> > > > 重新编译就可以了。。
> > > 
> > > 
> > > 您好，首先谢谢您的方法，很有效的解决了前几个依赖安装问题。 可是后面几个java环境的安装就不能简单的把压缩文件解压后添加workspace了，还是会报错 no such package 请问您有解决方法吗，谢谢。
> > > 我把test内容注释掉了，跳过此处编译，可以编译pagerank
> > > 这个问题解决了吗？ 这几个java的问题怎么解决
> 
> 我们采用的方法是 先在有外网的机器上 进行 bazel build 然后把cache目录中的external目录 直接拷贝出来 在你没有外网的机器上拷贝这个目录到相应位置即可
对的，我们当时也是类似的解决方法，让有权限的人把外网的东西弄到内网来。。。
