### ISSUE TITLE
社区发现算法有个问题

### ISSUE THREAD

**Issue by liwenhui-soul** [Tencent/plato#102]
按照louvain社区发现算法的逻辑，第i个节点加入某社区之后，第i+1个节点就得知道第i个节点加入的社区。这一点如果是串行程序就没什么问题，但是分布式执行的话，两个节点可能不在一个partition，那么就没办法实时的获取前一个节点的动作。
在同一个进程中，do_change 在try_change之后执行，这没问题，但从partition获取的信息再执行do_change，就没办法保证它一定是在try_change之后执行的。
请问这个问题你们是怎么考虑的？

**Comment by sdj222555** [comment]
这里并行算法你可以认为是串行算法的近似，会有一定的取舍。

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
