### ISSUE TITLE
定时脚本每天三台服务器并行跑plato算法任务，当天起脚本跑没问题，第二天之后就会出现permission denied

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#107]
每天定时跑plato  fast_unfolding_simple的脚本如下:
跑fast_unfolding_simple设置的mpich servers 是三台服务器，已经打通服务器之间的免密登陆。
当天启动脚本跑算法都没问题，第二天之后每天都出现 permission denied，如果当天再重启脚本，也是没问题的。
看起来是脚本的方式启动MPI任务，第二天之后就无法获取远程机器的免密秘钥导致的permission denied，但是我不太清楚在plato/scripts下面的算法脚本中，如何指定参数，才能不出现permission denied？

如果是scp 远程机器 这种可以指定-i identity_file，但plato调用的mpiexec 这种 如何指定秘钥参数访问远程机器？

#!/bin/bash
source /etc/profile
source /home/plato/.bash_profile
source /home/plato/.bashrc
log=/home/plato/run_lovain.log

while true
do
    # 获取当前时间，格式是时分，例如当前是上午8:00，hh=800
    hh=`date '+%H%M'`
    # 早上10:00 开始运行lovain算法
    if [ $hh -ge 1000 -a $hh -le 1003 ]
    then
        out_time=`date '+%Y-%m-%d-%H:%M'`
        echo " $out_time execute run_lovain.sh " >> $log 2>&1

        source /etc/profile
        source /home/plato/.bash_profile
        source /home/plato/.bashrc
        /bin/sh /home/plato/scripts/run_lovain.sh >> $log 2>&1
        sleep 180  
    fi

    sleep 60 #休息60s 

done

fast_unfolding_simple算法脚本run_lovain.sh

#!/bin/bash
source /etc/profile
source /home/plato/.bash_profile
source /home/plato/.bashrc

MAIN="/home/plato/plato-master/bazel-bin/example/fast_unfolding_simple" # process name
SERVERS="/home/plato/plato-master/servers" # mpich servers  **3台机器**

WNUM=3
WCORES=1

INPUT=${INPUT:='hdfs://cluster8/user/db/urs_edge_for_plato_unweighted'}
OUTPUT=${OUTPUT:='hdfs://cluster8/user/idc/hive_db/yanxuan_risk.db/idc_lovain_unweighted_graph'}

OUTER_ITERATION=${OUTER_ITERATION:=3}
INNER_ITERATION=${INNER_ITERATION:=2}

NOT_ADD_REVERSED_EDGE=${NOT_ADD_REVERSED_EDGE:=false}  # let plato auto add reversed edge or not

ALPHA=-1
PART_BY_IN=false

EPS=${EPS:=0.0001}
DAMPING=${DAMPING:=0.85}
ITERATIONS=${ITERATIONS:=100}

export MPIRUN_CMD=${MPIRUN_CMD:='/opt/mpich-3.2.1/bin/mpiexec.hydra'}
export JAVA_HOME=${APP_JAVA_HOME:='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-11.b12.el7.x86_64/'}
export HADOOP_HOME=${APP_HADOOP_HOME:='/opt/hadoop-2.7.4'}
export HADOOP_CONF_DIR="${HADOOP_HOME}/etc/hadoop"

PARAMS+=" --threads ${WCORES}"
PARAMS+=" --input ${INPUT} --output ${OUTPUT}"
PARAMS+=" --outer_iteration ${OUTER_ITERATION}"
PARAMS+=" --inner_iteration ${INNER_ITERATION}"

export LD_LIBRARY_PATH=${JAVA_HOME}/jre/lib/amd64/server:${LD_LIBRARY_PATH}

export CLASSPATH=${HADOOP_HOME}/etc/hadoop:`find ${HADOOP_HOME}/share/hadoop/ | awk '{path=path":"$0}END{print path}'`
export LD_LIBRARY_PATH="${HADOOP_HOME}/lib/native":${LD_LIBRARY_PATH}

chmod 777 ${MAIN}
${MPIRUN_CMD} -n ${WNUM} -f ${SERVERS} ${MAIN} ${PARAMS}
exit $?

**Comment by ustcyu** [comment]
免密登录和启动MPI任务应该是分开的，建议先跑通免密登录脚本。

**Comment by fengsen-neu** [comment]
> 免密登录和启动MPI任务应该是分开的，建议先跑通免密登录脚本。

环境问题，免密被限制了，已经可以跑了。多谢~
