### ISSUE TITLE
Plato支持正则查询吗？

### ISSUE THREAD

**Issue by heshuguo** [Tencent/plato#112]
如题。

**Comment by ustcyu** [comment]
Plato目前提供离线图计算和图表示学习的能力，暂不支持图查询。

**Comment by heshuguo** [comment]
也不支持节点带属性的运算是吧？

**Comment by ustcyu** [comment]
是否支持节点属性，这个是算法本身决定的。Plato目前只有少数算法（比如Metapath-Randomwalk）需要节点属性。
