### ISSUE TITLE
plato连通子图读入本地文件错误

### ISSUE THREAD

**Issue by mengxifeng** [Tencent/plato#113]
input和output文件是本地数据的时候，出错
F0828 14:53:08.244323 153670 dcsc.hpp:361] Check failed: edge->src_ < graph_info.vertices_ 
*** Check failure stack trace: ***
    @           0x4668d8  google::LogMessage::Fail()
    @           0x46681d  google::LogMessage::SendToLog()
    @           0x4661c2  google::LogMessage::Flush()
    @           0x469b3f  google::LogMessageFatal::~LogMessageFatal()
    @           0x41da06  _ZNSt17_Function_handlerIFvSt8functionIFbiRKjEEEZN5plato6dcsc_tINS6_7empty_tENS6_29sequence_balanced_by_source_tESaINS6_10adj_unit_tIS8_EEEE15load_from_cacheINS6_18edge_block_cache_tIS8_jEEEEiRKNS6_12graph_info_tERT_EUlS4_E0_E9_M_invokeERKSt9_Any_dataOS4_
    @           0x40f412  _ZNSt17_Function_handlerIFvSt8functionIFbiRKjEEEZN5plato6dcsc_tINS6_7empty_tENS6_29sequence_balanced_by_source_tESaINS6_10adj_unit_tIS8_EEEE19load_from_traversalEjS0_IFvbEES0_IS5_ES0_IFvS0_IFbiRKNS6_11edge_unit_tIS8_jEEEEEEEUlS4_E0_E9_M_invokeERKSt9_Any_dataOS4_
    @           0x42d5ae  _ZN5plato14fine_grain_bspIjEEiSt8functionIFvS1_IFbiRKT_EEEES1_IFviRNS_10iarchive_tIS2_NS_13mem_istream_tEvE6pmsg_tEEENS_10bsp_opts_tES1_IFvvEESI_._omp_fn.9
    @     0x7ff0137a743e  (unknown)
    @     0x7ff0142f76ba  start_thread
    @     0x7ff0134d54dd  clone
Aborting.
Backtrace:
  0x00000000004614a8
  0x000000000046072e
  0x00000000004608d1
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138e
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000035437
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000037038
  0x000000000046f600
  0x00000000004668d6
  0x000000000046681b
  0x00000000004661c0
  0x0000000000469b3d
  0x000000000041da04
  0x000000000040f410
  0x000000000042d5ac
  /usr/lib/x86_64-linux-gnu/libgomp.so.1+0x000000000000f43c
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b8
  /lib/x86_64-linux-gnu/libc.so.6+0x00000000001074db

**Comment by ustcyu** [comment]
Plato需要顶点是从0开始连续编码的。

**Comment by mengxifeng** [comment]
所有plato涉及的算法都是这样，还是只有连通子图啊

**Comment by mengxifeng** [comment]
> Plato需要顶点是从0开始连续编码的。

所有plato涉及的算法都是这样，还是只有连通子图啊

**Comment by ustcyu** [comment]
基本都是需要编码的，只有少量算法不需要

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
