### ISSUE TITLE
docker下的编译问题：coverage_output_generator-v2.0.zip: connect timed out

### ISSUE THREAD

**Issue by wuchaodzxx** [Tencent/plato#118]
**docker下执行./build.sh，报以下错误：**

`wuchao@6fd23dde1719:/data$ ./build.sh
+++ dirname ./build.sh
++ realpath .
+ ROOT_DIR=/data
+ cd /data
+ '[' == clean ']'
./build.sh: line 8: [: ==: unary operator expected
+ export CC=/data/3rd/mpich/bin/mpicxx
+ CC=/data/3rd/mpich/bin/mpicxx
+ export BAZEL_LINKOPTS=-static-libstdc++
+ BAZEL_LINKOPTS=-static-libstdc++
+ export LD_LIBRARY_PATH=:/data/3rd/hadoop2/lib
+ LD_LIBRARY_PATH=:/data/3rd/hadoop2/lib
+ bazel test plato/...
Loading: 
Loading: 0 packages loaded
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:216:1
INFO: Call stack for the definition of repository 'remote_coverage_tools' which is a http_archive (rule definition at /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /DEFAULT.WORKSPACE.SUFFIX:9:1
WARNING: Download from https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.0.zip failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'remote_coverage_tools':
   java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.0.zip] to /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/remote_coverage_tools/coverage_output_generator-v2.0.zip: connect timed out
Analyzing: 100 targets (0 packages loaded, 0 targets configured)
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:260:1
ERROR: /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/BUILD:4:1: @bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:all_lcov_merger_lib depends on @remote_coverage_tools//:all_lcov_merger_tools_deploy.jar in repository @remote_coverage_tools which failed to fetch. no such package '@remote_coverage_tools//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.0.zip] to /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/remote_coverage_tools/coverage_output_generator-v2.0.zip: connect timed out
**ERROR: Analysis of target '//plato/engine/test:walk' failed; build aborted: no such package '@remote_coverage_tools//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.0.zip] to /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/remote_coverage_tools/coverage_output_generator-v2.0.zip: connect timed out**
INFO: Elapsed time: 71.297s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
`

**Comment by ustcyu** [comment]
linux开发环境需要能访问外网

**Comment by ustcyu** [comment]
[https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.0.zip] to /home/wuchao/.cache/bazel/_bazel_wuchao/4caa791091d21d23e63637080226f370/external/remote_coverage_tools/coverage_output_generator-v2.0.zip: connect timed out
请检查下这个问题

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
