### ISSUE TITLE
encountering file-not-found error when building examples

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#12]
when building examples with the script below
`BAZEL_LINKOPTS=-static-libstdc++ CC=mpicxx bazel build example/...`
an error is raised 
./plato/graph/base.hpp:36:18: fatal error: numa.h: No such file or director

**Comment by skyssj** [comment]
Same with https://github.com/Tencent/plato/issues/12

**Comment by jsycdut** [comment]
> Same with #12
lol, Same as #10, not 12
