### ISSUE TITLE
pagerank是否支持带权重的计算

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#120]
目前plato的pagerank算法的input/output是：
input: <src>,<dst>
output:<vertex_id>,<pagerank_value>

某些业务场景需要带权重的计算，请问是否支持？
input: <src>,<dst>,<weight>
output:<vertex_id>,<pagerank_value>

**Comment by ustcyu** [comment]
可以参考：https://github.com/Tencent/plato/blob/master/example/pagerank_weighted.cc

**Comment by fengsen-neu** [comment]
> 可以参考：https://github.com/Tencent/plato/blob/master/example/pagerank_weighted.cc

多谢~

**Comment by fengsen-neu** [comment]
> 可以参考：https://github.com/Tencent/plato/blob/master/example/pagerank_weighted.cc

多谢~
