### ISSUE TITLE
plato算法GNC和GraphSage开源计划

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#121]
请问，plato暂未开源的GNC和GraphSage算法是否会开源，进度计划是怎样的？
![image](https://user-images.githubusercontent.com/58256617/96818036-3fca5d80-1453-11eb-8c28-ccaddd08725e.png)
https://github.com/Tencent/plato/wiki

**Comment by ustcyu** [comment]
GCN和GraphSage等算法还在不断优化中，我们暂未明确开源时间，感谢对Plato的关注。

**Comment by fengsen-neu** [comment]
> GCN和GraphSage等算法还在不断优化中，我们暂未明确开源时间，感谢对Plato的关注。

好的，感谢回复
