### ISSUE TITLE
Metapath-based random walk 输入数据问题

### ISSUE THREAD

**Issue by AdRush** [Tencent/plato#122]
基于metapath 的random walk 输入数据是不是不需要编码？直接输入明文字符串可以吗 ?load_edges_cache_with_encode？

**Comment by ustcyu** [comment]
Metapath RandomWalk的输入数据需要编码，load_edges_cache_with_encoder虽然提供了内置编码的能力，但不支持字符串格式。

**Comment by AdRush** [comment]
编码的话，我看demo数据好像是不用从0开始连续编码这样对吧？

**Comment by ustcyu** [comment]
使用load_edges_cache_with_encoder可以不从0开始编码

**Comment by AdRush** [comment]
TEST(Walk, RandomWalkOnMultiTypes) {
+--- 12 lines: init_cluster_info();----------------------------------------------------------------------------------------------
  auto cache = plato::load_edges_cache<plato::empty_t>(&graph_info, "data/graph/non_coding_5_8.csv",
      plato::edge_format_t::CSV, plato::dummy_decoder<plato::empty_t>);
  plato::sparse_state_t<uint32_t, part_spec_t> v_types(graph_info.vertices_, partitioner);

  plato::load_vertices_state_from_path<uint32_t>("data/graph/non_coding_5_8_vertic.csv", plato::edge_format_t::CSV,
      partitioner, plato::uint32_t_decoder,
      [&](plato::vertex_unit_t<uint32_t>&& unit) {
        v_types.insert(unit.vid_, unit.vdata_);
      });

如上面的RandomWalkOnMultiTypes测试用例：non_coding_5_8.csv 里面是没有连续编码的数据，但是这里直接用在了这个场景下面，load_edges_cache 的参数里vid_encoder直接取的默认nullptr;

**Comment by ustcyu** [comment]
Metapath RandomWalk的输入数据需要保证：顶点为uint32，且不同类型的顶点不能重复。如果输入数据本身就符合上述两点要求，可以不用编码。

**Comment by AdRush** [comment]
了解了，多谢！

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
