### ISSUE TITLE
[Bug] weighted pagerank does not converge

### ISSUE THREAD

**Issue by sinnergarden** [Tencent/plato#127]
## 问题描述

用体量稍大的测试数据来跑 weighted pagerank 时，结果有一定概率不收敛，delta 先变小后变大。用小数据集测试 （100个点）以内，则没有这个问题。

更详细的log显示应该是由于 rank 泄露，但没有找到具体的原因。有一定几率结果收敛，但是详细log显示也有 rank 泄露的问题，只是不严重，（比如，只比init rank 增加了个位数，且一定次数 epoch 之后，遍不再泄露），所以算法仍然能收敛。

<img width="976" alt="Screenshot 2020-12-23 at 11 45 51 AM" src="https://user-images.githubusercontent.com/14290819/102957284-fd85d100-4514-11eb-8cac-4353e90bf03f.png">

<img width="901" alt="Screenshot 2020-12-23 at 12 00 17 PM" src="https://user-images.githubusercontent.com/14290819/102957824-7174a900-4516-11eb-97f0-3097fabb9fa2.png">

## 疑问

- 算法和数据应该都是固定的，没有随机成分，为何每次运行的结果不一样 ？

## 复现

脚本和对应的测试数据
 
```
#!/bin/bash

set -ex

CUR_DIR=$(realpath $(dirname $0))
ROOT_DIR=$(realpath $CUR_DIR/..)
cd $ROOT_DIR

MAIN="$ROOT_DIR/bazel-bin/example/pagerank_weighted" # process name
WNUM=1
WCORES=20

INPUT=${INPUT:="test_edge_list_with_weight.csv"}
OUTPUT=${OUTPUT:="/tmp/pagerank"}
IS_DIRECTED=${IS_DIRECTED:=false}
EPS=${EPS:=0.0001}
DAMPING=${DAMPING:=0.85}
ITERATIONS=${ITERATIONS:=100}

# param
PARAMS+=" --threads ${WCORES}"
PARAMS+=" --input ${INPUT} --output ${OUTPUT} --is_directed=${IS_DIRECTED}"
PARAMS+=" --iterations ${ITERATIONS} --eps ${EPS} --damping ${DAMPING}"

# mpich
MPIRUN_CMD=${MPIRUN_CMD:="$ROOT_DIR/3rd/mpich/bin/mpiexec.hydra"}

# test
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$ROOT_DIR/3rd/hadoop2/lib

# output dir
mkdir -p $OUTPUT

# run
${MPIRUN_CMD} -n ${WNUM} ${MAIN} ${PARAMS}

echo ">>>>>>>>>>>output>>>>>>>>>>>>>>"
ls -lh $OUTPUT

```

[test_edge_list_with_weight.txt](https://github.com/Tencent/plato/files/5733173/test_edge_list_with_weight.txt)

**Comment by ustcyu** [comment]
谢谢指出，该问题已知，会尽快修复。

**Comment by ustcyu** [comment]
bug已修复，关闭本issue，如有问题，请reopen。
