### ISSUE TITLE
Plato怎么离线安装？

### ISSUE THREAD

**Issue by jievince** [Tencent/plato#130]
如题， 需要在无外网环境下安装。

**Comment by actcwlf** [comment]
可以在有网环境下构建好后使用 docker save 导出，再在相应环境中导入。同时将第三方库打包进镜像的Dockerfile可参考
https://github.com/actcwlf/plato/tree/iso-docker/docker
ref：
[`docker save`](https://docs.docker.com/engine/reference/commandline/save/)
[`docker load`](https://docs.docker.com/engine/reference/commandline/load/)

**Comment by jievince** [comment]
了解，非常感谢🙏

**Comment by jievince** [comment]
> https://github.com/actcwlf/plato/tree/iso-docker/docker

你好， 这样离线安装的是docker镜像？ 我是想直接安装到裸机上

**Comment by actcwlf** [comment]
如果不使用docker的话目前没有提供一键安装的功能，需要参考 `docker/install-dependencies.sh` 和 `3rdtools.sh`的代码手动安装。考虑到复杂性和潜在的问题，还是建议使用docker的方式运行plato
