### ISSUE TITLE
plato 跑算法时输出的日志保存在哪里？

### ISSUE THREAD

**Issue by jievince** [Tencent/plato#132]

**Comment by actcwlf** [comment]
plato默认不会输出日志到文件，如有需要可以注释算法代码中的`google::LogToStderr();`，并在运行时通过指定[`--log_dir`、`--logtostderr`](https://github.com/google/glog/#setting-flags)等参数控制
```C++
void init(int argc, char** argv) {
  gflags::ParseCommandLineFlags(&argc, &argv, true);
  google::InitGoogleLogging(argv[0]);
  //google::LogToStderr();
}
```
[代码来源](https://github.com/Tencent/plato/blob/8cf12c0a497a6a8d89da8ec05e82d1af7141d32c/example/bfs_simple.cc#L47)

**Comment by jievince** [comment]
谢谢🙏
