### ISSUE TITLE
有没有开源SLPA,BMLPA算法

### ISSUE THREAD

**Issue by yangyi423** [Tencent/plato#136]
请问大佬有没有 开源关于重叠社区的算法呢 （SLPA,BMLPA）   因为在example中只看到了lpa的代码
期待回复~

**Comment by ustcyu** [comment]
感谢对Plato的关注，暂未开源重叠社区算法。

**Comment by yangyi423** [comment]
那如果我们需要基于柏拉图 做重叠社区的图计算   需要我们自己实现相关的算法吗？还是说后续会开源？ 比较着急。。。

**Comment by ustcyu** [comment]
需要自己实现，SLPA可以基于LPA算法修改。
LPA算法例子：https://github.com/Tencent/plato/blob/master/example/lpa.cc

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
