### ISSUE TITLE
How to develop and debug plato

### ISSUE THREAD

**Issue by jsycdut** [Tencent/plato#138]
Currently, I know that Plato is written in c++ 11 standards, and build with Bazel, I can understand the basic logic behind the code. Since I am working with Cmake and Clion and not familiar with Bazel. Can you tell us how you debug Plato and the way you develop it(by what ide? maybe emacs?),  thanks a million :)

**Comment by actcwlf** [comment]
Personally, I prefer visual studio code as development tool. When debugging the code I use glog to show runtime information
(e.g. [bfs.cc](https://github.com/Tencent/plato/blob/9c6b3d25840383baa3e6483b5abc3226486d86f4/example/bfs.cc#L72)). Hope this will be help for you : )

**Comment by jievince** [comment]
Hi @actcwlf , which vsc extension do you use for function jump?

**Comment by jsycdut** [comment]
> Personally, I prefer visual studio code as development tool. When debugging the code I use glog to show runtime information
> (e.g. [bfs.cc](https://github.com/Tencent/plato/blob/9c6b3d25840383baa3e6483b5abc3226486d86f4/example/bfs.cc#L72)). Hope this will be helpful for you : )

That's really kind of you, thanks for your help.

After exploring the way to build and debug plato for a week, now I can use vscode, emacs, clion, gdb and bazel to build and debug plato now.

**Comment by jsycdut** [comment]
> Hi @actcwlf , which vsc extension do you use for function jump?

Maybe c/c++ plugin in vscode

**Comment by actcwlf** [comment]
> > Hi @actcwlf , which vsc extension do you use for function jump?
> 
> Maybe c/c++ plugin in vscode

Yes I use c/c++ plugin. You can specify `includePath` in config of the plugin

**Comment by jsycdut** [comment]
We could be friends in reality if you guys feel the same.  You can contact me via` jsycdut@gmail.com` , telegram is available for me, the accout is `19494647973`, or WeChat if you like.

<p align="center">
  <img width=250px src="https://github.com/jsycdut/photos/blob/master/contact/wechat.jpg?raw=true"/>
</p>
