### ISSUE TITLE
missing dependency declarations

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#14]
when building examples with the script below
BAZEL_LINKOPTS=-static-libstdc++ CC=mpicxx bazel build example/...
an error is raised
ERROR: /home/xxxxxx/plato-master/plato/graph/BUILD:3:1: undeclared inclusion(s) in rule '//plato/graph:base':
this rule is missing dependency declarations for the following files included by 'plato/graph/base.cc':
  '/home/xxxxxx/openmpi/include/mpi.h'
  '/home/xxxxxx/openmpi/include/mpi_portable_platform.h'

**Comment by xuguruogu** [comment]
Maybe use mpich instead of openmpi will solve your problem.

**Comment by WuWenQiangqwq** [comment]
use open-mpicxx instead of mpicxx will solve your problem.

**Comment by matricer** [comment]
@xuguruogu thx, the problem seemed to be solved.
