### ISSUE TITLE
关于nstepdegrees算法的使用

### ISSUE THREAD

**Issue by lanerbean** [Tencent/plato#143]
你好  咨询以下几个关于nstepdegrees的问题：
1.这个算法需要的actives参数是个csv文件吗？  每一个行写一个节点吗？
2.本来要用local模式跑的，因为数据在本地，但是要求我设置classpath  这是因为什么呢？该如何设置
3.我才用集群模式跑的时候  结果目录里面没有文件。

我把输入的参数，脚本和日志放上来，希望大佬能回复一下。
![WechatIMG15](https://user-images.githubusercontent.com/18582787/111131710-7c8a2300-85b3-11eb-8f7a-2a77e349e603.jpeg)
![WechatIMG16](https://user-images.githubusercontent.com/18582787/111131717-7f851380-85b3-11eb-8924-a5810b23c1f5.jpeg)

**Comment by lanerbean** [comment]
求大佬指点一下，比较急。。。。。

**Comment by actcwlf** [comment]
1. actives可以是csv文件的路径，每一行指定要计算的顶点，也可以指定为`ALL`，表示计算全部的顶点
2. local模式请参考run_pagerank_local.sh进行修改，提示需要classpath可能是使用的集群模式的脚本
3. 可能是因为没有进行顶点的计算，所以没有输出结果

**Comment by lanerbean** [comment]
您好，刚才采用集群模式的脚本，并且将actives参数设置为ALL，执行完之后结果文件依旧是空的，请问还有没有其它的因素导致了这个问题？

**Comment by actcwlf** [comment]
能否提供一下完整的运行日志和相关的运行环境？

**Comment by lanerbean** [comment]
执行脚本：
![脚本1](https://user-images.githubusercontent.com/18582787/111268346-1f03de00-8668-11eb-96fa-c60fba3659a5.jpeg)
![脚本2](https://user-images.githubusercontent.com/18582787/111268353-21663800-8668-11eb-9f86-bbd22083156c.jpeg)

运行日志：
![日志1](https://user-images.githubusercontent.com/18582787/111268416-393dbc00-8668-11eb-8fcd-02d711dd2a10.jpeg)
![日志2](https://user-images.githubusercontent.com/18582787/111268418-3b077f80-8668-11eb-9d6b-b39010aa6793.jpeg)

**Comment by lanerbean** [comment]
求大佬们指点

**Comment by ustcyu** [comment]
fix输出问题：https://github.com/Tencent/plato/pull/146

**Comment by lanerbean** [comment]
大佬您好，感谢您对这个问题的处理，目前我已经能采用local模式的脚本执行nstepdegrees算法了，并且也产生了结果数据。但是我得到的结果和预计的有一些出入，求大佬指点，感谢！
我在测试时使用的图结构（无向图）如下：
![image](https://user-images.githubusercontent.com/18582787/112414432-fdd47900-8d5c-11eb-972f-2593a411cc14.png)

得到的结果如下：
0,11,11
3,11,11
4,11,11
6,11,11
7,11,11
8,11,11
5,11,11
1,11,11
10,11,11
2,11,11
9,11,11

**Comment by lanerbean** [comment]
我采用的图是无向图：
![image](https://user-images.githubusercontent.com/18582787/112414899-d631e080-8d5d-11eb-8ee5-965126eea08f.png)

**Comment by actcwlf** [comment]
你指定step参数了吗，如果没有的话默认会走完可走的所有点
