### ISSUE TITLE
关于betweenness算法的使用

### ISSUE THREAD

**Issue by lanerbean** [Tencent/plato#144]
请问betweenness算法的-chosen参数是什么意思？该如何使用这个参数？能举一个简单的例子说明吗？

**Comment by lanerbean** [comment]
您好，我采用无向图进行betweenness centrality计算时，结果是正确的；但是采用有向图进行计算时，节点的betweenness centrality都是0，请问，这是为什么？

**Comment by actcwlf** [comment]
chosen参数指定计算哪个点的betweenness centrality，若为-1则计算最大联通分量中顶点的值。不过目前版本只支持chosen为-1（默认值），稍后会有更新，感谢指出。现有的实现中会先计算联通分量再计算，但在有向图中计算联通分量存在问题，所以只支持在无向图中计算

**Comment by ustcyu** [comment]
chosen参数bug fix：https://github.com/Tencent/plato/pull/145

**Comment by lanerbean** [comment]
感谢大佬们的解答！
