### ISSUE TITLE
`plato/util/test/stream.cc` 是个空的文件吗？

### ISSUE THREAD

**Issue by darionyaphet** [Tencent/plato#149]
`plato/util/test/stream.cc` 是个空的文件吗？

![image](https://user-images.githubusercontent.com/4414314/112417622-eef0c500-8d62-11eb-9b7c-336755318f9d.png)

**Comment by actcwlf** [comment]
这个暂时还没有添加具体的测试用例

**Comment by darionyaphet** [comment]
了解
