### ISSUE TITLE
plato可以打包成rpm/deb包安装吗？

### ISSUE THREAD

**Issue by jievince** [Tencent/plato#150]
源码编译太麻烦，也不想用docker打包安装

**Comment by ustcyu** [comment]
暂未提供rpm/deb包安装方式，建议使用docker编译，也是比较方便的。

**Comment by jievince** [comment]
> 暂未提供rpm/deb包安装方式，建议使用docker编译，也是比较方便的。

离线生产环境，并且禁用docker

**Comment by ustcyu** [comment]
那么也可以尝试直接编译部署，如果遇到问题可在issue中提出，我们会协助解决。

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
