### ISSUE TITLE
plato集群模式必须要配置ssh免密吗

### ISSUE THREAD

**Issue by jievince** [Tencent/plato#151]

**Comment by ustcyu** [comment]
请问是遇到了哪方面的问题吗？

**Comment by ustcyu** [comment]
请问是遇到什么问题了吗？

**Comment by jievince** [comment]
> 请问是遇到什么问题了吗？

有的生产环境因为某些原因禁用ssh。
mpi接口貌似是基于ssh的

**Comment by ustcyu** [comment]
可以通过SSH的方式登录到服务器启动MPI程序，也可以不通过SSH，直接通过YARN等方式将MPI程序调度起来，具体要看你的资源调度方式。
