### ISSUE TITLE
多实例跑PageRank，CPU使用不均衡问题

### ISSUE THREAD

**Issue by longmingg** [Tencent/plato#156]
起了3个实例(单实例10核)跑PageRank，只有1个实例能用到这么多，其他两个只能用到3-5核，这是不是意味着这两个实例会比第一个实例速度要慢，而plato每个迭代同步的形式会造成木桶效应呢？

**Comment by abasi20** [comment]
我也遇到这个问题，跑pagerank时，cpu只能跑到80%左右，不知道是不是由于发送阶段使用了随机方法引起的cpu使用下降。

**Comment by longmingg** [comment]
后续发现主要是各实例之间计算量不均衡，计算量少的实例执行速度较快，有一定的时间在等待其他实例执行，所以相对而言CPU占用率没有那么高
