### ISSUE TITLE
连通图算法2 个不相连节点处于同一 community

### ISSUE THREAD

**Issue by hluculent** [Tencent/plato#158]
![image](https://user-images.githubusercontent.com/15646558/123807074-1e930880-d922-11eb-8f15-6a505c61c384.png)

输入 src-id  与 dst-id 单向边组合，使用 默认参数运行 cgm
运行的结果将 6 度不相交的 2 个节点归于同一个社区：

以某 2 个节点为例：
初始数据：2 个节点相关的边为 228 条
![image](https://user-images.githubusercontent.com/15646558/123807492-7893ce00-d922-11eb-88b1-f1a7d716dfc4.png)

结果输出的边也为 228 条：
![image](https://user-images.githubusercontent.com/15646558/123807696-ad078a00-d922-11eb-93aa-14aea5d4557b.png)

属于 32 号社区，但是 这两个节点不存在路径关联。
![image](https://user-images.githubusercontent.com/15646558/123809336-1b008100-d924-11eb-84c4-9bd4bae63664.png)

且 32 号社区存在千万级别的节点
![image](https://user-images.githubusercontent.com/15646558/123809595-526f2d80-d924-11eb-8407-e3ed385f4607.png)

**Comment by hluculent** [comment]
其中 1 个顶点 查询 10 度联通关系 返回 31 个节点，且最深也只有 3 度，说明该点 连通图只有 31 个节点。
![image](https://user-images.githubusercontent.com/15646558/123892201-b6c5d780-d98c-11eb-8606-8423d3a678a3.png)

**Comment by skyssj** [comment]
能否将详细的程序执行参数打印一下呢？您上面贴的参数有可能被传入的参数所覆盖。

**Comment by hluculent** [comment]
> 能否将详细的程序执行参数打印一下呢？您上面贴的参数有可能被传入的参数所覆盖。
开始执行脚本 到 具体计算前的日志如下：没有看到参数
![image](https://user-images.githubusercontent.com/15646558/123903567-80df1e00-d9a1-11eb-8740-5e536f8239ef.png)

**Comment by hluculent** [comment]
#!/bin/bash
source /etc/profile
source /home/webedit/.bash_profile
source /home/webedit/.bashrc

MAIN="../plato/plato-master/bazel-bin/example/cgm_simple" # process name
SERVERS="../plato/plato-master/servers" # mpich servers

#MAIN="../bazel-bin/example/cgm_simple" # process name
#SERVERS="../servers" # mpich servers

WNUM=3
WCORES=1

INPUT=${INPUT:="hdfs://hive_db/yxplato.db/table/ds=`date +%Y-%m-%d`"}

OUTPUT=${OUTPUT:="hdfs://hive_db/yxplato.db/table/ds=`date +%Y-%m-%d`"}



#IS_DIRECTED=${IS_DIRECTED:=false}

NOT_ADD_REVERSED_EDGE=${NOT_ADD_REVERSED_EDGE:=false}  # let plato auto add reversed edge or not

ALPHA=-1
PART_BY_IN=false

EPS=${EPS:=0.0001}
DAMPING=${DAMPING:=0.85}
ITERATIONS=${ITERATIONS:=100}

export MPIRUN_CMD=${MPIRUN_CMD:='/opt/mpich-3.2.1/bin/mpiexec.hydra'}
export JAVA_HOME=${APP_JAVA_HOME:='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-11.b12.el7.x86_64/'}
export HADOOP_HOME=${APP_HADOOP_HOME:='/opt/hadoop-2.7.4'}
export HADOOP_CONF_DIR="${HADOOP_HOME}/etc/hadoop"

PARAMS+=" --threads ${WCORES}"
PARAMS+=" --input ${INPUT} --output ${OUTPUT}"
PARAMS+=" --output_method="all_edges""
#PARAMS+=" --is_directed ${IS_DIRECTED}"
#PARAMS+=" --epoch ${EPOCH}"
#PARAMS+=" --step ${STEP}"
#PARAMS+=" --rate ${RATE}"
# PARAMS+=" --iterations ${ITERATIONS} --eps ${EPS} --damping ${DAMPING}"

# env for JAVA && HADOOP
export LD_LIBRARY_PATH=${JAVA_HOME}/jre/lib/amd64/server:${LD_LIBRARY_PATH}

# env for hadoop
export CLASSPATH=${HADOOP_HOME}/etc/hadoop:`find ${HADOOP_HOME}/share/hadoop/ | awk '{path=path":"$0}END{print path}'`
export LD_LIBRARY_PATH="${HADOOP_HOME}/lib/native":${LD_LIBRARY_PATH}

chmod 777 ./${MAIN}
${MPIRUN_CMD} -n ${WNUM} -f ${SERVERS} ./${MAIN} ${PARAMS}
exit $?

**Comment by hluculent** [comment]
问题定位：离线图计算比实时图查询多了一个节点，剔除该节点后 ok 了
