### ISSUE TITLE
pagerank算法报错 exit code 9

### ISSUE THREAD

**Issue by zhenghw0226** [Tencent/plato#159]
![Screenshot 2021-07-01 at 11 22 29 AM](https://user-images.githubusercontent.com/38321956/124060041-b7c73980-da5e-11eb-845e-6face326f3b2.png)

跑pagerank时报错显示exit code 9， 请问是哪里有问题？

**Comment by skyssj** [comment]
看错误信息是被kill 了，OOM了？

**Comment by zhenghw0226** [comment]
> 看错误信息是被kill 了，OOM了？

是的是的 感谢
