### ISSUE TITLE
cannot find -lstdc++ when building examples 

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#17]
when building examples with the script below
`BAZEL_LINKOPTS=-static-libstdc++ CC=mpicxx bazel build example/...`
an error is raised

> Use --sandbox_debug to see verbose messages from the sandbox
> /usr/bin/ld.gold: error: cannot find -lstdc++

**Comment by xuguruogu** [comment]
`yum install glibc-static libstdc++-static `

You need to install static c++ library.

**Comment by matricer** [comment]
@xuguruogu thx, problem solved~
