### ISSUE TITLE
Intersection Test Failed

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#19]
We follow the test instruction: 
`BAZEL_LINKOPTS=-static-libstdc++ CC=mpicxx LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/3rd/hadoop2/lib bazel test --test_env=LD_LIBRARY_PATH plato/...`
and get the result below:
![fail1](https://user-images.githubusercontent.com/16053879/69053098-8d974400-0a00-11ea-8d0d-4c8aae3a0519.png)
there are 3 warnings and 1 failure. The failure log gives
![fail2](https://user-images.githubusercontent.com/16053879/69053478-655c1500-0a01-11ea-8ceb-ebe6a792e8b8.png)

Is the failure acceptable? Does "plato" work normally?

**Comment by xuguruogu** [comment]
`cat /proc/cpuinfo`

Could you please give your cpuinfo.

**Comment by matricer** [comment]
@xuguruogu 
![failed](https://user-images.githubusercontent.com/16053879/69061545-406f9e00-0a11-11ea-9c82-e226916b6c22.png)

**Comment by xuguruogu** [comment]
> @xuguruogu
> `cat /proc/cpuinfo` gives
> ![failed](https://user-images.githubusercontent.com/16053879/69061545-406f9e00-0a11-11ea-9c82-e226916b6c22.png)
> Note that the CPU here has no avx2 && fma instruction sets.

SIMD based intersection needs avx2 instruction. You can also use plato except for mutual algorithm.

**Comment by matricer** [comment]
@xuguruogu thx
BTW, any plan to add conditional compilation to switch to non-avx2 code (e.g. sse)

**Comment by matricer** [comment]
@xuguruogu get it! thx very much~
