### ISSUE TITLE
Build Failed: link to libunwind error.

### ISSUE THREAD

**Issue by wzbxpy** [Tencent/plato#22]
when running BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx  bazel build example/...
### I met
`WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/command.profile.gz'
INFO: Analyzed 24 targets (42 packages loaded, 14017 targets configured).
INFO: Found 24 targets...
INFO: Deleting stale sandbox base /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox
ERROR: /home/tian/wzb/plato/example/BUILD:20:1: Linking of rule '//example:function_call' failed (Exit 1) mpicxx failed: error executing command 
  (cd /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox/linux-sandbox/6/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/tian/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx @bazel-out/k8-fastbuild/bin/example/function_call-2.params)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_Ux86_64_getcontext'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_init_local'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_get_reg'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_step'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 165.786s, Critical Path: 154.06s
INFO: 2 processes: 2 linux-sandbox.
FAILED: Build did NOT complete successfully`

### And I have installed  libunwind

**Comment by xuguruogu** [comment]
Glog links to libunwind atomically. You can remove libunwind to avoid the dependency. Or you can try to install libunwind-devel.

**Comment by wzbxpy** [comment]
> 
> 
> Glog links to libunwind atomically. You can remove libunwind to avoid the dependency. Or you can try to install libunwind-devel.

I am building palto on ubuntu 18.04.
And I have removed libunwind8 and libunwind-dev, but still build failed, and I haven't found  libunwind-devel for ubuntu.

**Comment by wzbxpy** [comment]
> 
> 
> Glog links to libunwind atomically. You can remove libunwind to avoid the dependency. Or you can try to install libunwind-devel.



> 
> 
> Glog links to libunwind atomically. You can remove libunwind to avoid the dependency. Or you can try to install libunwind-devel.

### there still have error when running test
~/wzb/plato$ BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/3rd/hadoop2/lib bazel test --test_env=LD_LIBRARY_PATH plato/...
INFO: Build option --test_env has changed, discarding analysis cache.
INFO: Analyzed 100 targets (24 packages loaded, 14343 targets configured).
INFO: Found 68 targets and 32 test targets...
ERROR: /home/tian/wzb/plato/plato/util/test/BUILD:147:1: Linking of rule '//plato/util/test:libsvm' failed (Exit 1) mpicxx failed: error executing command 
  (cd /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox/linux-sandbox/360/execroot/__main__ && \
  exec env - \
    LD_LIBRARY_PATH=:/home/tian/wzb/plato/3rd/hadoop2/lib \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx -o bazel-out/k8-fastbuild/bin/plato/util/test/libsvm -g -fPIC -static-libstdc++ -static-libgcc -fopenmp -Wall '-std=c++11' -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -static-libstdc++ -Wl,@bazel-out/k8-fastbuild/bin/plato/util/test/libsvm-2.params)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox: mpicxx failed: error executing command 
  (cd /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox/linux-sandbox/360/execroot/__main__ && \
  exec env - \
    LD_LIBRARY_PATH=:/home/tian/wzb/plato/3rd/hadoop2/lib \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx -o bazel-out/k8-fastbuild/bin/plato/util/test/libsvm -g -fPIC -static-libstdc++ -static-libgcc -fopenmp -Wall '-std=c++11' -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -pass-exit-codes -static-libstdc++ -Wl,@bazel-out/k8-fastbuild/bin/plato/util/test/libsvm-2.params)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
3rd/glog/lib/libglog.a(libglog_la-logging.o):logging.cc:function __static_initialization_and_destruction_0(int, int): error: undefined reference to 'google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 333.525s, Critical Path: 332.20s
INFO: 23 processes: 23 linux-sandbox.
FAILED: Build did NOT complete successfully
//plato/algo/bnc/test:test_bnc                                        NO STATUS
//plato/algo/cgm/test:test_cgm                                        NO STATUS
//plato/algo/cnc/test:test_cnc                                        NO STATUS
//plato/algo/hanp/test:test_hanp                                      NO STATUS
//plato/algo/hyperanf/test:test_hyperanf                              NO STATUS
//plato/algo/nstepdegrees/test:test_nstepdegrees                      NO STATUS
//plato/engine/test:walk                                              NO STATUS
//plato/graph/state/test:allgather_state                              NO STATUS
//plato/graph/state/test:dense_state                                  NO STATUS
//plato/graph/state/test:sparse_state                                 NO STATUS
//plato/graph/state/test:vertex_cache                                 NO STATUS
//plato/graph/structure/test:bcsr                                     NO STATUS
//plato/graph/structure/test:cbcsr                                    NO STATUS
//plato/graph/structure/test:dcsc                                     NO STATUS
//plato/graph/structure/test:edge_cache                               NO STATUS
//plato/graph/structure/test:hnbbcsr                                  NO STATUS
//plato/graph/structure/test:tcsr                                     NO STATUS
//plato/graph/test:message_passing                                    NO STATUS
//plato/graph/test:parsers                                            NO STATUS
//plato/graph/test:structure                                          NO STATUS
//plato/parallel/test:broadcast                                       NO STATUS
//plato/parallel/test:bsp                                             NO STATUS
//plato/parallel/test:parallel                                        NO STATUS
//plato/util/test:aliastable                                          NO STATUS
//plato/util/test:archive                                             NO STATUS
//plato/util/test:bitmap                                              NO STATUS
//plato/util/test:intersection                                        NO STATUS
//plato/util/test:mmap_alloc                                          NO STATUS
//plato/util/test:object_buffer                                       NO STATUS
//plato/util/test:test_hyperloglog                                    NO STATUS
//plato/util/test:thread_local_object                                 NO STATUS

it seems like glog didn't correct installed

**Comment by lorinlee** [comment]
@wzbxpy you can try add "-lunwind" in glog's BUILD file, but it just works on debian, will fail on centos by my test. cc @xuguruogu

**Comment by lorinlee** [comment]
@wzbxpy  Oh sorry, I haven't read the context seriously, you can take a look at my pull request to solve the gflag's problem. It works on debian, but will fail on centos.

**Comment by lorinlee** [comment]
By my further testing, I find my PR only works on debian8. As for debian9, it needn't to do so, sorry for that.
