### ISSUE TITLE
should the node id of graph data be continous from zero?

### ISSUE THREAD

**Issue by ChangbingChen** [Tencent/plato#25]
when running run_pagerank.sh on the open twitter data(twitter_rv.zip, 41 million nodes and 1.47 billion edges), i got some failed logs.
```
check failed: edge->dst_ < graph_info.vertices_
```

plato/plato/graph/structure/dcsc.hpp, line 362
```
  auto foreach_dests = [&](bsp_send_callback_t<vid_t> send) {
    auto traversal = [&](size_t, edge_unit_spec_t* edge) {
      CHECK(edge->src_ < graph_info.vertices_);
      CHECK(edge->dst_ < graph_info.vertices_);

      send(partitioner_->get_partition_id(edge->src_, edge->dst_), edge->dst_);
      if (false == graph_info.is_directed_) {  // cache friendly
        send(partitioner_->get_partition_id(edge->dst_, edge->src_), edge->src_);
      }
      return true;
    };

    size_t chunk_size = 64;
    while (cache.next_chunk(traversal, &chunk_size)) {
    }
  };
```

should the node id of graph data be continous from zero?

**Comment by skyssj** [comment]
ChangbingChen,

Yes, most algorithm in Plato needs node-id be continous from 0 to \#N - 1.

**Comment by ChangbingChen** [comment]
is there any good solution to assign continous ids for massive nodes, eg. 1billion ?

**Comment by xuguruogu** [comment]
We consider to remove the demand the node id should be continous from zero.
