### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by RustRw** [Tencent/plato#31]
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
+ BAZEL_VERSION=1.2.0
+ BAZEL_INSTALLER_FIL=bazel-1.2.0-installer-linux-x86_64.sh
+ BAZEL_INSTALLER=/tmp/bazel-1.2.0-installer-linux-x86_64.sh
+ curl -o /tmp/bazel-1.2.0-installer-linux-x86_64.sh -sSL https://github.com/bazelbuild/bazel/releases/download/1.2.0/bazel-1.2.0-installer-linux-x86_64.sh
curl: (6) Could not resolve host: github.com

**Comment by xuguruogu** [comment]
This may due to your docker proxy not configured right. Please refer docker proxy doc: [https://docs.docker.com/network/proxy/](https://docs.docker.com/network/proxy/).

You can also simply run following cmd to use built ubuntu image. Please run the cmd under project root dir.
```
docker run -v $(pwd):/data -e USER_NAME=$(id -un) -e USER_ID=$(id -u) -it --rm platograph/plato-dev:ubuntu.16.04
```
