### ISSUE TITLE
请问集群如何运行

### ISSUE THREAD

**Issue by oushu1liwenhui1** [Tencent/plato#35]
看到run_pagerank.sh里面设了一些环境变量，INPUT,OUTPUT之类。
我理解mpi应该是通过ssh对每个节点执行可执行文件，那么是不是每个节点都要将这些环境变量设一遍，也就是说单纯运行run_pagerank.sh是无法进行多节点计算的，是不是这样？

**Comment by xuguruogu** [comment]
mpi作为一种通用编程接口，多节点运行方式取决于具体的mpi实现。如果使用mpich，可以参考[https://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager](https://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager)
