### ISSUE TITLE
Could not find compiler set in environment variable CC:    /3rd/mpich/bin/mpicxx

### ISSUE THREAD

**Issue by arron7856d** [Tencent/plato#42]
系统是centos 7
./build.sh 的时候出错，看了一下：3rd/mpich/bin/目录下缺少mpicxx文件，这个文件是编译过程中生成的吗，如何解决这个问题？我已经将cmake和make都升级到了最新版本。
以下是完整报错信息：
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at /usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:56 (message):
  Could not find compiler set in environment variable CC:

  /3rd/mpich/bin/mpicxx.
Call Stack (most recent call first):
  CMakeLists.txt:100 (enable_language)

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/tseg/lfy/plato/.downloads/gflags-2.2.1/build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/tseg/lfy/plato/.downloads/gflags-2.2.1/build/CMakeFiles/CMakeOutput.log".
'CXXFLAGS=-fPIC cmake .. -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/tseg/lfy/plato/3rd/gflags-2.2.1' exec failed with code 1, abort install process!

**Comment by xuguruogu** [comment]
CC被错误的设置到环境变量里了。如何复现这个错误？另外请贴出执行`env`命令的结果。

**Comment by arron7856d** [comment]
感谢回复！
执行bazel build example/... 这行代码不成功，所以我重新执行了一次bulid.sh clean，执行过程中出现的该问题。
我的env
XDG_SESSION_ID=9508
SPARK_HOME=/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark
HOSTNAME=mirage-20.novalocal
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.103.240.44 3216 22
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(base) 
OLDPWD=/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/hadoop
SSH_TTY=/dev/pts/0
USER=tseg
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/home/tseg/anaconda3/bin/conda
_CE_CONDA=
MAIL=/var/spool/mail/tseg
PATH=/home/tseg/anaconda3/bin:/home/tseg/anaconda3/condabin:/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/home/tseg/anaconda3/bin:/home/tseg/.local/bin:/home/tseg/bin
ANTLR4_HOME=/usr/local/lib/antlr-4.7.2-complete.jar
CONDA_PREFIX=/home/tseg/anaconda3
PWD=/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/hadoop/sbin
LANG=zh_CN.UTF-8
_CE_M=
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/tseg
GOROOT=/usr/local/go
CONDA_PYTHON_EXE=/home/tseg/anaconda3/bin/python
LOGNAME=tseg
CLASSPATH=:/usr/local/lib/antlr-4.7.2-complete.jar
XDG_DATA_DIRS=/home/tseg/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
SSH_CONNECTION=10.103.240.44 3216 192.168.111.199 22
CONDA_DEFAULT_ENV=base
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/1002
DISPLAY=localhost:10.0
_=/usr/bin/env

遗憾的是，现在依然没有build 成功，我在 bazel test /plato/...时遇到了以下问题。
ERROR: /home/tseg/lfy/plato-master/plato/graph/BUILD:3:1: C++ compilation of rule '//plato/graph:base' failed (Exit 1) gcc failed: error executing command 
  (cd /home/tseg/.cache/bazel/_bazel_tseg/fdaa8f340d192701f665e97531a41123/sandbox/processwrapper-sandbox/299/execroot/__main__ && \
  exec env - \
    PATH=/home/tseg/anaconda3/bin:/home/tseg/anaconda3/condabin:/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/home/tseg/anaconda3/bin:/home/tseg/.local/bin:/home/tseg/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/plato/graph/_objs/base/base.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/plato/graph/_objs/base/base.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -Ibazel-out/k8-fastbuild/bin/3rd/glog/_virtual_includes/glog -Ibazel-out/k8-fastbuild/bin/3rd/libunwind/_virtual_includes/libunwind -Ibazel-out/k8-fastbuild/bin/3rd/gflags/_virtual_includes/gflags -isystem plato/graph -isystem bazel-out/k8-fastbuild/bin/plato/graph -isystem plato/util -isystem bazel-out/k8-fastbuild/bin/plato/util -isystem 3rd/boost/include -isystem bazel-out/k8-fastbuild/bin/3rd/boost/include -isystem plato/util/libcuckoo -isystem bazel-out/k8-fastbuild/bin/plato/util/libcuckoo -O2 -Wall '-std=c++11' -g -fPIC -static-libstdc++ -static-libgcc -fopenmp -Wall '-std=c++11' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c plato/graph/base.cc -o bazel-out/k8-fastbuild/bin/plato/graph/_objs/base/base.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
In file included from plato/graph/base.cc:22:0:
./plato/graph/base.hpp:35:17: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
                 ^
compilation terminated.

**Comment by xuguruogu** [comment]
bulid.sh clean会删除3rd目录内容。你需要确保`./3rdtools.sh distclean && ./3rdtools.sh install`执行成功，然后执行`./build.sh`。大多数构建系统会检查`CC`环境变量，不要尝试export到你所使用的shell中。

**Comment by arron7856d** [comment]
谢谢，这个问题现在解决了。以后我不会尝试单独执行在build.sh中的某些指令
