### ISSUE TITLE
运行例程错误Error occurred during initialization of vm

### ISSUE THREAD

**Issue by arron7856d** [Tencent/plato#45]
运行run_ragerank_local.sh通过
运行run_ragerank.sh时报错，错误如图
![image](https://user-images.githubusercontent.com/44742154/70401995-cd37d580-1a6c-11ea-9688-a129795c7ac0.png)
我并未设置关于/3rd/jni6.0/这个路径的环境变量，为何要去这里找libjava.so，这个问题如何解决？
以下是我系统的env
XDG_SESSION_ID=15905
SPARK_HOME=/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark
HOSTNAME=mirage-20.novalocal
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.103.240.44 14266 22
CONDA_SHLVL=0
SSH_TTY=/dev/pts/0
USER=tseg
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
CONDA_EXE=/home/tseg/anaconda3/bin/conda
_CE_CONDA=
MAIL=/var/spool/mail/tseg
PATH=/home/tseg/anaconda3/condabin:/home/tseg/lfy/jdk1.8.0_191/bin:/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/bin:/home/tseg/anaconda3/bin:/home/tseg/.local/bin:/home/tseg/bin
ANTLR4_HOME=/usr/local/lib/antlr-4.7.2-complete.jar
PWD=/home/tseg/lfy/jdk1.8.0_191/jre/lib/amd64
JAVA_HOME=/home/tseg/lfy/jdk1.8.0_191
LANG=zh_CN.UTF-8
_CE_M=
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/tseg
GOROOT=/usr/local/go
CONDA_PYTHON_EXE=/home/tseg/anaconda3/bin/python
LOGNAME=tseg
CLASSPATH=:/usr/local/lib/antlr-4.7.2-complete.jar
XDG_DATA_DIRS=/home/tseg/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
SSH_CONNECTION=10.103.240.44 14266 192.168.111.199 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/1002
DISPLAY=localhost:10.0
OLDPWD=/home/tseg/lfy/plato
_=/usr/bin/env
我根据集群环境修改的sh文件
![image](https://user-images.githubusercontent.com/44742154/70402309-e3926100-1a6d-11ea-9962-3c8c0c2eedc3.png)

**Comment by xuguruogu** [comment]
检查你的配置，是否成功加载到了HADOOP的libhdfs.so。可以在run_pagerank.sh的`${MPIRUN_CMD} -n ${WNUM} ./${MAIN} ${PARAMS}`之前加一行命令`ldd ${MAIN}`查看

**Comment by arron7856d** [comment]
感谢回复
![image](https://user-images.githubusercontent.com/44742154/70403905-39b5d300-1a73-11ea-988d-d70c52bcda47.png)
如上面所示，我的环境是centos7，hadoop 安装的CDH发行版，所以libhdfs.so不在$HADOOP_HOME/lib/native下

**Comment by arron7856d** [comment]
抱歉，错误仍然存在，在我更改了可以指向libhdfs.so.0.0.0 的LD_LIBRARY_PATH后

**Comment by xuguruogu** [comment]
> 抱歉，错误仍然存在，在我更改了可以指向libhdfs.so.0.0.0 的LD_LIBRARY_PATH后

要使用Hadoop的hdfs路径

**Comment by arron7856d** [comment]
是要HDFS datanode的存储路径，还是HDFS可执行文件的路径？我都试过了，没有解决
![image](https://user-images.githubusercontent.com/44742154/70432996-81604d00-1abb-11ea-8cf5-59e938388b27.png)

**Comment by xuguruogu** [comment]
确认一下jvm链接位置是否正确。看起来Java路径没有配置正确

**Comment by arron7856d** [comment]
我确认run_pagerank.sh 和run_pagerank_local.sh 两次提交`ldd ${MAIN}`出来的值，除了libhdfs.so的位置不同，其他都是一样的，检查过java路径正确。还有其他方法调试吗？

**Comment by xuguruogu** [comment]
similar with #48
