### ISSUE TITLE
Meet segmentation fault when generate_dense_in_degrees 

### ISSUE THREAD

**Issue by JianyuLi** [Tencent/plato#46]
![image](https://user-images.githubusercontent.com/4198752/70405899-bc419100-1a79-11ea-9407-c2eace4bd6a3.png)

Try to run a 2-step degree search on a big graph, which loaded from HDFS into 3 computing hosts:
/home/lijianyu/plato/3rd/mpich/bin/mpiexec.hydra -f /home/lijianyu/plato/scripts/hosts -n 3 /home/lijianyu/plato/bazel-bin/example/nstepdegrees --threads 48 --input hdfs://xxx/data/dump --output hdfs://xxx/nstep_degree --is_directed=true --step 2 --type out --actives /home/lijianyu/plato/active.list
I1206 16:37:30.456579 64890 base.hpp:179] thread support level provided by MPI:
I1206 16:37:30.456629 64890 base.hpp:182] MPI_THREAD_MULTIPLE
I1206 16:37:30.456643 64890 base.hpp:211] threads: 48
I1206 16:37:30.456646 64890 base.hpp:212] sockets: 2
I1206 16:37:30.456648 64890 base.hpp:213] partitions: 3
I1206 16:37:30.456650 64890 nstepdegrees.cc:135] partitions: 3 partition_id: 0
I1206 16:37:30.456694 152776 nstepdegrees.cc:135] partitions: 3 partition_id: 2
I1206 16:37:30.456832 65244 nstepdegrees.cc:135] partitions: 3 partition_id: 1
I1206 16:37:32.038390 64890 detail.hpp:155] partition-0, file-count: 3318
I1206 16:37:32.038425 64890 detail.hpp:155] partition-1, file-count: 2065
I1206 16:37:32.038429 64890 detail.hpp:155] partition-2, file-count: 2644
![image](https://user-images.githubusercontent.com/4198752/70406621-5c98b500-1a7c-11ea-9292-7b4947f9600d.png)
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 152776 RUNNING AT xxx
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
Each host of these three computing servers has 512GB memory, so the total memory is enough to hold the whole graph in memory.

**Comment by xuguruogu** [comment]
As shown in #37 #25 , nstepdegrees only support uint32_t vertex id, at the same time, vertex id should be continous from 0.

**Comment by JianyuLi** [comment]
Hi gu,

The vertex id is in the range of uint32_t, as you could see, the number of vertices is 958024187.
I1206 18:26:17.698092 64890 structure.hpp:1009] edges:        49850805036
I1206 18:26:17.698096 64890 structure.hpp:1010] vertices:     958024187
I1206 18:26:17.698098 64890 structure.hpp:1011] max_v_id:     4294967295

So here the problem is due to vertex id isn't continuous?

**Comment by JianyuLi** [comment]
And even if the vertex id isn't continuous, it seems that the generate_dense_in_degrees should't occur segment fault here, since it just traverse edge info from EdgeCache and add the vertex degrees accordingly.
![image](https://user-images.githubusercontent.com/4198752/70422429-b4e4ac80-1aa6-11ea-961d-ca695fcf2911.png)

And from the previous gdb output, we could see the edge info got from EdgeCache is corrupted.
![image](https://user-images.githubusercontent.com/4198752/70422583-e9f0ff00-1aa6-11ea-9f4b-eef8d83d4e0d.png) 
Generally speaking, we should finish the generate_dense_in_degrees action and meet the failed check assertion as mentioned in #25 
      CHECK(edge->src_ < graph_info.vertices_);
      CHECK(edge->dst_ < graph_info.vertices_);

**Comment by xuguruogu** [comment]
https://github.com/Tencent/plato/blob/bb15d552a469e415b61b2f5d5c7d21d04854dde9/plato/graph/structure.hpp#L268-L284

It does run into corruption, as `graph_info.max_v_i_` is assigned the max value of uint32_t, and `graph_info.max_v_i_ + 1` overflows. We do not mark this as bug currently. Remap the graph to make vertex id continuous is one of the best practice.

**Comment by JianyuLi** [comment]
Ok, will try to map the vertex id to continuous ones.
