### ISSUE TITLE
Plato运行lpa和tree_stat_simple样例出错

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#48]
安装完运行run_pagerank_local.sh和run_pagerank.sh（修改input/output）均通过。
但是运行lpa和tree_stat_simple样例出错
 ./bazel-bin/example/lpa --input /test/home/hadoop/tar/plato-master/data/graph/v100_e2150_ua_c3.csv --output /tmp/lpa
![image](https://user-images.githubusercontent.com/58256617/70786661-233bae80-1dc8-11ea-934d-a62923f18277.png)
![image](https://user-images.githubusercontent.com/58256617/70786580-f4253d00-1dc7-11ea-95e7-09e6f3cb4c76.png)

 ./bazel-bin/example/tree_stat_simple --input /test/home/hadoop/tar/plato-master/data/graph/v100_e2150_ua_c3.csv --output /tmp/tree
![image](https://user-images.githubusercontent.com/58256617/70786515-c9d37f80-1dc7-11ea-8682-a1511353e01d.png)

运行node2vec_randomwalk通过
./bazel-bin/example/node2vec_randomwalk --input /test/home/hadoop/tar/plato-master/data/graph/v100_e2150_ua_c3.csv --output /tmp/node2vec

我的java环境设置/etc/profile
![image](https://user-images.githubusercontent.com/58256617/70786808-6e55c180-1dc8-11ea-8853-7c2288dac14c.png)
![image](https://user-images.githubusercontent.com/58256617/70786865-875e7280-1dc8-11ea-98a8-ba787bfe5250.png)

问题：我设置了java环境，为什么还要到路径/test/home/hadoop/tar/plato-master/3rd/jni6.0/中找so文件？为什么同样的环境，有的用例能跑过，有的却跑不过呢？我看了#45的问题，#45最后也没有解决如何配置。

我继续通过ln -s的方式将/usr/lib/jvm/java-8-openjdk-amd64/中的so软链接到/test/home/hadoop/tar/plato-master/3rd/jni6.0/路径，最后还是报错
![image](https://user-images.githubusercontent.com/58256617/70787233-38650d00-1dc9-11ea-95d1-a6cb67f4a450.png)

**Comment by xuguruogu** [comment]
https://github.com/Tencent/plato/blob/f1a917241b10d339160414f2eba9c911877c6da4/scripts/run_pagerank.sh#L29

${JAVA_HOME}/jre/lib/amd64/server目录有这个so么

**Comment by fengsen-neu** [comment]
so在目录/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/，我之前已经添加过这个环境变量，仍然不行，并且我尝试将/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/下的so文件软链接到/test/home/hadoop/tar/plato-master/3rd/jni6.0/路径最后还是报错，如原文最后截图。
![image](https://user-images.githubusercontent.com/58256617/70790305-c5ab6000-1dcf-11ea-88a5-442cc314f9a8.png)
![image](https://user-images.githubusercontent.com/58256617/70790268-b0cecc80-1dcf-11ea-859c-1098fe6cb579.png)

**Comment by xuguruogu** [comment]
为什么要把`${JAVA_HOME}/jre/lib/amd64/server`修改为`${JAVA_HOME}/jre/lib/amd64`

**Comment by fengsen-neu** [comment]
我改了，报了新问题core dumped
![image](https://user-images.githubusercontent.com/58256617/70874219-244d2580-1fec-11ea-8a2b-98205ae68acc.png)

![image](https://user-images.githubusercontent.com/58256617/70874209-15667300-1fec-11ea-87fc-c4a52fc8d188.png)

**Comment by xuguruogu** [comment]
> ./bazel-bin/example/tree_stat_simple --input /test/home/hadoop/tar/plato-master/data/graph/v100_e2150_ua_c3.csv --output /tmp/tree

注意到这是本地文件的输入输出，目前并非所有算法都支持了本地fs。

tree_stat只访问hdfs。
https://github.com/Tencent/plato/blob/f1a917241b10d339160414f2eba9c911877c6da4/example/tree_stat_simple.cc#L60-L74

pagerank 使用了`plato::thread_local_fs_output`，支持由`hdfs://`前缀判断访问hdfs还是本地fs。
https://github.com/Tencent/plato/blob/f1a917241b10d339160414f2eba9c911877c6da4/example/pagerank.cc#L193-L200

**Comment by fengsen-neu** [comment]
我将input/output改成hdfs文件，也是同样的错误。
./bazel-bin/example/tree_stat_simple --input hdfs://innosqlv3e-stable-test1:9000/plato_data/raw_graph_10_9.csv --output hdfs://innosqlv3e-stable-test1:9000/plato_data/pagerank_raw_graph_10_9
![image](https://user-images.githubusercontent.com/58256617/70902955-ce529f00-2038-11ea-8c8c-66860664433a.png)

**Comment by fengsen-neu** [comment]
问题已经解决：
lpa和tree_stat_simple需要使用hdfs文件做input，并且需要将命令写到脚本里执行（需要设置相关环境才可以，如果像我之前单独执行命令也不行）。非常感谢@kent的帮助。
![image](https://user-images.githubusercontent.com/58256617/70958157-49f13200-20b3-11ea-8cf8-f46c6ba5db51.png)
执行结果
![image](https://user-images.githubusercontent.com/58256617/70958249-9b012600-20b3-11ea-9a20-cb6326bb34dd.png)
![image](https://user-images.githubusercontent.com/58256617/70958269-ac4a3280-20b3-11ea-8094-45af7cf1cc8b.png)

**Comment by fengsen-neu** [comment]
问题已经解决：
lpa和tree_stat_simple需要使用hdfs文件做input，并且需要将命令写到脚本里执行（需要设置相关环境才可以，如果像我之前单独执行命令也不行）。非常感谢@kent的帮助。
![image](https://user-images.githubusercontent.com/58256617/70958157-49f13200-20b3-11ea-8cf8-f46c6ba5db51.png)
执行结果
![image](https://user-images.githubusercontent.com/58256617/70958249-9b012600-20b3-11ea-9a20-cb6326bb34dd.png)
![image](https://user-images.githubusercontent.com/58256617/70958269-ac4a3280-20b3-11ea-8094-45af7cf1cc8b.png)
