### ISSUE TITLE
run  build.sh has error on centos 7 

### ISSUE THREAD

**Issue by mullerhai** [Tencent/plato#51]
Analyzing: 100 targets (33 packages loaded, 0 targets configured)
ERROR: /opt/plato/plato/parallel/BUILD:38:1: no such package '3rd/glog': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /opt/plato/3rd/glog and referenced by '//plato/parallel:bsp'
ERROR: Analysis of target '//plato/parallel:bsp' failed; build aborted: no such package '3rd/glog': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /opt/plato/3rd/glog
INFO: Elapsed time: 2.747s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 18 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (43 packages loaded, 18 targets configured)

**Comment by mullerhai** [comment]
ERROR: /opt/plato/plato/parallel/test/BUILD:3:1: no such package '3rd/yas': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /opt/plato/3rd/yas and referenced by '//plato/parallel/test:parallel'
ERROR: Analysis of target '//plato/parallel/test:parallel' failed; build aborted: no such package '3rd/yas': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /opt/plato/3rd/yas
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by xuguruogu** [comment]
As shown in the readme, install dependencies and third party libraries is required before build plato. https://github.com/Tencent/plato#dependencies

```
# install compile dependencies.
sudo ./docker/install-dependencies.sh
# download and build staticlly linked libraries.
./3rdtools.sh distclean && ./3rdtools.sh install
```
