### ISSUE TITLE
如何控制plato图算法的内存使用？

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#53]
我在运行node2vec_randomwalk算法2千万点，10亿边的数据时，由于内存占用较大导致服务器中其他进程OOM了。
查看了plato图算法程序的--help以及mpiexec的使用方法https://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager，没有找到控制内存使用大小的参数。
请问plato是否有配置参数或者运行参数能控制图算法运行时的内存占用大小？

**Comment by skyssj** [comment]
柏拉图或 mpich 默认的资源管理程序是没有办法控制自身的内存使用，我的理解这方面的工作应当是交由集群的资源管理软件来限制（例如：yarn node manage ）。此外，node2vec_randomwalk 存在一个参数可以适当的减少内存使用，您可以尝试设置 `--rate=0.01` 或是更小值。

**Comment by xuguruogu** [comment]
plato将所有数据加载到内存中，并不能自适应系统内存。内存隔离方面的工作应该由容器负责。

**Comment by wenzhenghu** [comment]
@skyssj @xuguruogu 好的。不过这样的话，就需要提前预估一个节点跑起来后，需要多少内存，以便yarn或容器的管理程序能够分配足够内存给plato节点，否则内存不够是否plato自身进程也会被干掉。李总提到plato将数据都加载到内存，那么有办法提供个内存占用比例关系呢，比如一共n G数据，3个plato节点并行计算，那么可能占用 x * n/3，这个x应该怎么确定。两位大佬目前是否评估过。我们也会尝试看代码分析分析。

**Comment by frapuccino** [comment]
@wenzhenghu 粗略的估算了一下metapath randomwalk和node2vec randomwalk的内存占用情况情况，以下公式可做参考（其中顶点数和边数(文件数据行数)可以精确计算，位图开销较小，保守预留1G，footprint开销500亿边规模时(15台机器)每台机器10多G左右（具体按照实际运行数据为准））：
metapath_rw: E(数据文件边数)，V(顶点数)，F(footprint缓存开销),  beta(位图开销)， T（类型数）
有向无权：
（(14+4T)V+12E）+ F + beta个字节
有向有权：
（(14+4T)V+28E） + F + beta个字节
无向无权：
((14+4T)V+16E) + F + beta个字节
无向有权：
((14+4T)V + 44E) + F + beta个字节

node2vec:  E(数据文件边数)，V(顶点数)，F(footprint缓存开销),  beta(位图开销)
有向无权: 
（10V+12E）+ F + beta个字节
有向有权：
（10V+28E） + F + beta个字节
无向无权：
(10V+16E) + F + beta个字节
无向有权：
(10V + 44E) + F + beta个字节

**Comment by frapuccino** [comment]
以上时总空间占用情况的公式，负载较均衡时每台机器内存占用可按照（total / 机器数）计算

**Comment by wenzhenghu** [comment]
@frapuccino 谢谢，我们估算下，有问题再请教你们。

**Comment by xuguruogu** [comment]
这里的n*E，考虑了图加载过程中的cache内存占用。如果想进一步降低内存占用 ，可以参考：#34

**Comment by fengsen-neu** [comment]
@frapuccino 我用公式计算2亿顶点，6亿边的无向有权图使用node2vec算法预估内存是：
（10*2亿+44*6亿）+6*(150/500)G+1G=29.3GB
但实际测试时使用8进程并发（两台机器，每台4进程），总共需要78.532GB内存，相差比较大。
![image](https://user-images.githubusercontent.com/58256617/71572726-7d07dc80-2b1b-11ea-9c05-4c785f97c270.png)
![image](https://user-images.githubusercontent.com/58256617/71572744-990b7e00-2b1b-11ea-95bd-e0c65cabba69.png)

另外我又测试了一组2千万顶点，10亿边的无向有权图跑node2vec算法，公式计算内存结果和实际观察差不多。
公式计算：45GB
实际内存：39.147GB

请问公式计算内存与实际内存不一定相符该如何处理？不准的情况还有其他办法估算吗？

**Comment by xuguruogu** [comment]
图算法都很难水平扩展。最佳方式是单进程资源尽量多。这样会接近内存估计

**Comment by fengsen-neu** [comment]
Plato高性能分布式图计算框架，单进程不符合实际使用场景，实际使用时需要多台机器多进程并发，如果分布式并发计算的场景内存估计不准确，还是会造成内存不足啊？

**Comment by fengsen-neu** [comment]
我用单进程测试了一会2亿顶点，6亿边的无向有权图，还没跑完，内存已经远超预估值29.3GB了。单进程估计值还是不准确。
![image](https://user-images.githubusercontent.com/58256617/71576230-e9d6a300-2b2a-11ea-92a0-e0714367fb07.png)

**Comment by fengsen-neu** [comment]
我用单机单进程测试了一下，测试仍在跑，目前实际使用内存63GB，已经远超预估值29.3GB了。单进程预估值与实际值误差仍很大。
![image](https://user-images.githubusercontent.com/58256617/71576480-ceb86300-2b2b-11ea-8565-741850bc4f05.png)

**Comment by xuguruogu** [comment]
> @frapuccino @xuguruogu 我用公式计算2亿顶点，6亿边的无向有权图使用node2vec算法预估内存是：
> （10x2亿+44x6亿）+6x(150/500)G+1G=29.3GB
> 但实际测试时使用8进程并发（两台机器，每台4进程），总共需要78.532GB内存，相差比较大。
> ![image](https://user-images.githubusercontent.com/58256617/71572726-7d07dc80-2b1b-11ea-9c05-4c785f97c270.png)
> ![image](https://user-images.githubusercontent.com/58256617/71572744-990b7e00-2b1b-11ea-95bd-e0c65cabba69.png)
> 
> 另外我又测试了一组2千万顶点，10亿边的无向有权图跑node2vec算法，公式计算内存结果和实际观察差不多。
> 公式计算：45GB
> 实际内存：39.147GB
> 
> 请问公式计算内存与实际内存不一定相符该如何处理？不准的情况还有其他办法估算吗？

(10*0.2+44*0.6+12*0.6+1) / 8 = 4.575G

单个进程预估只需要4.5G，这个数值太小了。高性能计算中，BSP通信队列，缓存等，都会有一些固定开销（可以达到几个G的水平）。用更大的数据集测试得到的结果更有价值。

**Comment by fengsen-neu** [comment]
> > @frapuccino @xuguruogu 我用公式计算2亿顶点，6亿边的无向有权图使用node2vec算法预估内存是：
> > （10x2亿+44x6亿）+6x(150/500)G+1G=29.3GB
> > 但实际测试时使用8进程并发（两台机器，每台4进程），总共需要78.532GB内存，相差比较大。
> > ![image](https://user-images.githubusercontent.com/58256617/71572726-7d07dc80-2b1b-11ea-9c05-4c785f97c270.png)
> > ![image](https://user-images.githubusercontent.com/58256617/71572744-990b7e00-2b1b-11ea-95bd-e0c65cabba69.png)
> > 另外我又测试了一组2千万顶点，10亿边的无向有权图跑node2vec算法，公式计算内存结果和实际观察差不多。
> > 公式计算：45GB
> > 实际内存：39.147GB
> > 请问公式计算内存与实际内存不一定相符该如何处理？不准的情况还有其他办法估算吗？
> 
> (10*0.2+44*0.6+12*0.6+1) / 8 = 4.575G
> 
> 单个进程预估只需要4.5G，这个数值太小了。高性能计算中，BSP通信队列，缓存等，都会有一些固定开销（可以达到几个G的水平）。用更大的数据集测试得到的结果更有价值。

请教一下，公式中 12*0.6 的12是怎么算出来的，按照“footprint开销500亿边规模时(15台机器)每台机器10多G左右”不是应该一亿边 150GB/500=0.3GB大小吗，6亿边的F = 6*0.3 GB。

**Comment by xuguruogu** [comment]
无向带权边12bit：src(uint32_t),dst(uint32_t),weight(float).

**Comment by fengsen-neu** [comment]
> 无向带权边12bit：src(uint32_t),dst(uint32_t),weight(float).

好的，多谢~
