### ISSUE TITLE
difference between fast_unfolding and fast_unfolding_with_density

### ISSUE THREAD

**Issue by yetingsky** [Tencent/plato#54]

**Comment by yetingsky** [comment]
which one I should use ? any reference?

**Comment by WuWenQiangqwq** [comment]
fast_unfolding_with_density has more communities, smaller communities, but consumes more memory 
https://arxiv.org/abs/1708.06810

**Comment by yetingsky** [comment]
Any reference for fast_unfolding ? I look for https://arxiv.org/abs/0803.0476, but delta Q formula not match `try_change` function in `louvian.hpp`

**Comment by xuguruogu** [comment]
The formula above is not simply a copy of the pater [louvian](https://arxiv.org/abs/0803.0476). As shown in the paper, the author only give the `delta Q_add` formula. Leaving the `delta Q_remove` formula to be deducted by readers themselves. 

![image](https://user-images.githubusercontent.com/6092236/71401958-6cacb900-2666-11ea-904d-b31ee79cbff5.png)

![image](https://user-images.githubusercontent.com/6092236/71401980-7c2c0200-2666-11ea-8520-71414098e289.png)


We can get the total `delta Q` by adding `delta Q_add` and `delta Q_remove`.

![image](https://user-images.githubusercontent.com/6092236/71401985-82ba7980-2666-11ea-893c-4f40a7022deb.png)

https://github.com/Tencent/plato/blob/5a5fe991a2ab886a384074c9ce61adb6621627ca/plato/algo/fast_unfolding/louvain.hpp#L185-L188

**Comment by yetingsky** [comment]
> double)sigma_tot_[to]

thx!
