### ISSUE TITLE
Plato如何解决热点数据问题？

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#56]
2亿顶点，6亿边的无向有权图数据测试node2vec_random算法，MPICH4进程并发，发现有一个进程的CPU利用率较高454%，其他很低51%，请问plato如何解决热点数据性能问题？
![image](https://user-images.githubusercontent.com/58256617/71567147-d231f700-2af7-11ea-8050-6ef20f4d89f3.png)

**Comment by xuguruogu** [comment]
根据我们的经验，单进程资源足够大（比如>50G），不均衡问题是很少的。图算法大多不是线性水平扩展，单机多进程不利于图算法的并发。

**Comment by fengsen-neu** [comment]
那就是说如果用分布式计算，最好每台机器最好开一个进程这样用是吗？

**Comment by xuguruogu** [comment]
> 那就是说如果用分布式计算，最好每台机器最好开一个进程这样用是吗？

是这样的

**Comment by fengsen-neu** [comment]
但我测试用的物理机是200GB内存，我开了4个进程，平均每个进程也50GB了啊？
