### ISSUE TITLE
Any reference for david closeness and bader betweenness

### ISSUE THREAD

**Issue by yetingsky** [Tencent/plato#58]

**Comment by ustcyu** [comment]
hi, yeting, please describe your problem in detail

**Comment by yetingsky** [comment]
比如标准的 closeness 算法是需要求出每个点到其他所有点的距离（bavelas.hpp 这个文件实现的就是这个），但是在 david.hpp 文件的实现中，是先通过采样一些点，然后根据这些 sample 计算所有点的 closeness，想请问下采样这种做法有啥参考资料吗？

**Comment by yetingsky** [comment]
标准的 closeness 和 betweenness 计算量的确很大，柏拉图这种采样计算的做法我觉得是挺优雅的，但是不知道计算的结果是否近似准确。

**Comment by skyssj** [comment]
@yetingsky betweeness 近似解法的论文详见：https://www.cc.gatech.edu/fac/Milena.Mihail/WAW07.pdf
closeness 做法与betweeness做法类似。
采样数越多，准确率越高，在我们抽样的一个网络下，采样数达到1000时，近似closeness算法准确率为99.5%。

**Comment by yetingsky** [comment]
> @yetingsky betweeness 近似解法的论文详见：https://www.cc.gatech.edu/fac/Milena.Mihail/WAW07.pdf
> closeness 做法与betweeness做法类似。
> 采样数越多，准确率越高，在我们抽样的一个网络下，采样数达到1000时，近似closeness算法准确率为99.5%。

thx ~
