### ISSUE TITLE
Fix the "No space left on device" error in WSL

### ISSUE THREAD

**Issue by bowen-xu** [Tencent/plato#60]
Hi,
I install the plato in WSL Ubuntu, and run the test while there goes the error:
F0220 15:04:03.325654  1031 object_buffer.hpp:980] Check failed: -1 != num WARNING: ftruncate64 failed, err code: 28, err msg: No space left on device
I found the cause of this bug.

see the example code below:

```
int main(int argc, char** argv) {
  std::string cache_dir = ".cache_test/";
  boost::filesystem::create_directories(cache_dir);
  uint64_t capacity = std::min(512UL * GBYTES, boost::filesystem::space(cache_dir).capacity) / sizeof(char);
  plato::temporary_file_t file_(".cache_test/");
  uint64_t capacity_ = capacity;
  printf("capacity_=%lld\nsizeof(size_t)=%d\n512UL * GBYTES=%lld\n", capacity_, sizeof(size_t), 512UL * GBYTES);
  auto num = ftruncate64(file_.fd(), sizeof(char) * capacity_);
  printf("num = %d\n", num);
  return 1;
}
```

You'll find that the `boost::filesystem::space(cache_dir).capacity` is much larger than the space remaining in disk C: where the wsl ubuntu system is installed. I guess that that boost space function returns all the space of the hole physicks disk consisting of other logic disks.

So I modified the 512UL to 10UL (smaller than the space remainning in disk C:) and it goes correctly.

But it is obviously not the solution. 

Maybe we should check something related to system or logic disk?

**Comment by xuguruogu** [comment]
We test and use Plato in centos system. As mentioned in [wsl-file-system-support](https://docs.microsoft.com/en-us/archive/blogs/wsl/wsl-file-system-support), WSL(Windows Subsystem for Linux) use VolFs, which supports most features the Linux VFS provides. Howerever, the behavior maybe slightly different, which we are unfamiliar with. We suggest using native linux system for running or testing Plato.
