### ISSUE TITLE
50亿顶点，100亿边的无向有权图跑fast_unfolding_simple估算需要多少内存？能否提供类似#53的公式？

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#61]
麻烦问一下：50亿顶点，100亿边的无向有权图跑fast_unfolding_simple估算需要多少内存？能否提供类似#53的公式？

**Comment by xuguruogu** [comment]
6 * total_vertices * sizeof(int) +  4 * total_edges * sizeof(int) / machine_num

50亿定点超过了uint32最大范围，我们目前不支持。

**Comment by fengsen-neu** [comment]
感谢 xuguruogu
