### ISSUE TITLE
fast_unfolding_simple算法运行14亿顶点和14亿边的数据报MPIR_Bcast_binomial(250) 错误

### ISSUE THREAD

**Issue by fengsen-neu** [Tencent/plato#62]
在两台200G内存的物理机，每台机器4进程运行fast_unfolding_simple算法，无向有权图的顶点和边大小如下：
edges:        1422364002
vertices:     1477698024
load完数据之后，报如下MPI错误，请问是什么原因导致的？
![image](https://user-images.githubusercontent.com/58256617/75227701-a8403c80-57e9-11ea-874d-ab6bebc429f7.png)

**Comment by xuguruogu** [comment]
mpi集合通信的message size 要小于2GB。需要修改

**Comment by fengsen-neu** [comment]
> mpi集合通信的message size 要小于2GB。需要修改

请问预计多久会更新修复版本？

**Comment by xuguruogu** [comment]
目前我看到在structure.hpp文件中，有三个MPI_Allreduce使用有缺陷：
https://github.com/Tencent/plato/blob/2230af32641f9ae290480d7a86bf053f019aa253/plato/graph/structure.hpp#L259

https://github.com/Tencent/plato/blob/2230af32641f9ae290480d7a86bf053f019aa253/plato/graph/structure.hpp#L284

https://github.com/Tencent/plato/blob/2230af32641f9ae290480d7a86bf053f019aa253/plato/graph/structure.hpp#L321

bug修订应该是分多次操作，可以参考：
https://github.com/Tencent/plato/blob/2230af32641f9ae290480d7a86bf053f019aa253/plato/graph/structure/tcsr.hpp#L366-L370

**Comment by fengsen-neu** [comment]
不是很确定degrees.data() 和 all_degrees.data()参数的改法？是改成下面这样degrees.data() + i 么？
size_t chunk_size = 128 * 1024 * 1024;
size_t total_size = size_t(graph_info.max_v_i_) + 1;
for (size_t i = 0; i < total_size; i += chunk_size) {
  MPI_Allreduce(MPI_IN_PLACE, degrees.data() + i, std::min(chunk_size, total_size - i), get_mpi_data_type<T>(), MPI_SUM, MPI_COMM_WORLD);
}

**Comment by xuguruogu** [comment]
> 不是很确定degrees.data() 和 all_degrees.data()参数的改法？是改成下面这样degrees.data() + i 么？
> size_t chunk_size = 128 * 1024 * 1024;
> size_t total_size = size_t(graph_info.max_v_i_) + 1;
> for (size_t i = 0; i < total_size; i += chunk_size) {
> MPI_Allreduce(MPI_IN_PLACE, degrees.data() + i, std::min(chunk_size, total_size - i), get_mpi_data_type(), MPI_SUM, MPI_COMM_WORLD);
> }

看起来是的

**Comment by fengsen-neu** [comment]
改完跑还是有问题。
![image](https://user-images.githubusercontent.com/58256617/75244129-2f9ba900-5806-11ea-9105-9290b0ebe6f1.png)

**Comment by xuguruogu** [comment]
> 改完跑还是有问题。
> ![image](https://user-images.githubusercontent.com/58256617/75244129-2f9ba900-5806-11ea-9105-9290b0ebe6f1.png)

我看到有assert(!closed)关键字，判断应该是某一个进程异常关闭。可以看一下有没有core或者oom

**Comment by xuguruogu** [comment]
建议每台机器一个进程，否则会有内存浪费情况。

**Comment by fengsen-neu** [comment]
> > 改完跑还是有问题。
> > ![image](https://user-images.githubusercontent.com/58256617/75244129-2f9ba900-5806-11ea-9105-9290b0ebe6f1.png)
> 
> 我看到有assert(!closed)关键字，判断应该是某一个进程异常关闭。可以看一下有没有core或者oom
是OOM了
![image](https://user-images.githubusercontent.com/58256617/75305347-d0c74580-5880-11ea-9a92-20c93a10f4ea.png)

**Comment by fengsen-neu** [comment]
> 建议每台机器一个进程，否则会有内存浪费情况。

好的
