### ISSUE TITLE
failed to build from the source file.

### ISSUE THREAD

**Issue by patricxu** [Tencent/plato#65]
could you give us more documents about how to build from the scource file?

**Comment by xuguruogu** [comment]
Please give the error message to help us understand your problem.

**Comment by patricxu** [comment]
@xuguruogu 以下是执行./build.sh的部分输出。我在build.sh里移除了buid test语句（这部分也无法执行）。仅保留了build example。感谢

`+++ dirname ./build.sh
++ realpath .
+ ROOT_DIR=/home/pld_xuqi/plato-master
+ echo /home/pld_xuqi/plato-master
+ cd /home/pld_xuqi/plato-master
+ '[' == clean ']'
./build.sh: line 11: [: ==: unary operator expected
+ export CC=/home/pld_xuqi/plato-master/3rd/mpich/bin/mpicxx
+ CC=/home/pld_xuqi/plato-master/3rd/mpich/bin/mpicxx
+ export BAZEL_LINKOPTS=-static-libstdc++
+ BAZEL_LINKOPTS=-static-libstdc++
+ export LD_LIBRARY_PATH=:/home/pld_xuqi/plato-master/3rd/hadoop2/lib
+ LD_LIBRARY_PATH=:/home/pld_xuqi/plato-master/3rd/hadoop2/lib
+ bazel build example/...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Analyzing: 24 targets (1 packages loaded, 0 targets configured)
Analyzing: 24 targets (42 packages loaded, 341 targets configured)
INFO: Analyzed 24 targets (43 packages loaded, 14021 targets configured).
INFO: Found 24 targets...
INFO: Deleting stale sandbox base /home/pld_xuqi/.cache/bazel/_bazel_root/921527ef2c11208b3726ae6ad8186f6f/san
dbox

[57 / 281] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /home/pld_xuqi/plato-master/example/BUILD:515:1: Linking of rule '//example:encode_simple' failed (E
xit 1) mpicxx failed: error executing command
  (cd /home/pld_xuqi/.cache/bazel/_bazel_root/921527ef2c11208b3726ae6ad8186f6f/sandbox/processwrapper-sandbox/1/execr
oot/__main__ && \
  exec env - \
    LD_LIBRARY_PATH=:/home/pld_xuqi/plato-master/3rd/hadoop2/lib \
    PATH=/opt/anaconda3/bin:/usr/local/bin:/usr/bin \
    PWD=/proc/self/cwd \
  /home/pld_xuqi/plato-master/3rd/mpich/bin/mpicxx @bazel-out/k8-fastbuild/bin/example/encode_simple-2.params)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_S3rd_Shadoop2_Chdfs-dynamic___U3rd_Shadoop2_Slib/l
ibhdfs.so:1:17: syntax error, unexpected $end
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_S3rd_Shadoop2_Chdfs-dynamic___U3rd_Shadoop2_Slib/l
ibhdfs.so: not an object or archive
./plato/util/hdfs.hpp:118: error: undefined reference to 'hdfsRead'
./plato/util/hdfs.hpp:83: error: undefined reference to 'hdfsOpenFile'
./plato/util/hdfs.hpp:88: error: undefined reference to 'hdfsGetPathInfo'
./plato/util/hdfs.hpp:93: error: undefined reference to 'hdfsFreeFileInfo'
./plato/graph/detail.hpp:141: error: undefined reference to 'hdfsListDirectory'
./plato/graph/detail.hpp:148: error: undefined reference to 'hdfsFreeFileInfo'
./plato/util/hdfs.hpp:122: error: undefined reference to 'hdfsWrite'
./plato/util/hdfs.hpp:122: error: undefined reference to 'hdfsWrite'
./plato/util/hdfs.hpp:100: error: undefined reference to 'hdfsFileIsOpenForWrite'
./plato/util/hdfs.hpp:105: error: undefined reference to 'hdfsCloseFile'
./plato/util/hdfs.hpp:101: error: undefined reference to 'hdfsFlush'
./plato/util/hdfs.hpp:100: error: undefined reference to 'hdfsFileIsOpenForWrite'
./plato/util/hdfs.hpp:101: error: undefined reference to 'hdfsFlush'
./plato/util/hdfs.hpp:105: error: undefined reference to 'hdfsCloseFile'
./plato/util/hdfs.hpp:100: error: undefined reference to 'hdfsFileIsOpenForWrite'
./plato/util/hdfs.hpp:105: error: undefined reference to 'hdfsCloseFile'
./plato/util/hdfs.hpp:101: error: undefined reference to 'hdfsFlush'
bazel-out/k8-fastbuild/bin/plato/util/_objs/hdfs/hdfs.pic.o:hdfs.cc:function plato::hdfs_t::get_hdfs(): error: undefi
ned reference to 'hdfsNewBuilder'
`

**Comment by patricxu** [comment]
it turned out to be the missing deps in example/BUILD which should be:
cc_binary(
      name = "encode_simple",
     ....
    deps = [
        "//other/deps",
        .....
        "//3rd/hadoop2:hdfs,
    ]
)
