### ISSUE TITLE
能否解释一下一些代码的细节

### ISSUE THREAD

**Issue by liwenhui-soul** [Tencent/plato#66]
aggregate_message函数里，将当前partition的图的数据读出来，然后又按vid获取其所属的partition，将数据发出去。这样的话，不就是传给自己吗，如果是这样，岂不是多此一举？

**Comment by patricxu** [comment]
请问你编译成功了吗

**Comment by xuguruogu** [comment]
参考Gemini的论文，https://coolerzxw.github.io/data/publications/gemini_osdi16.pdf。spread的原意是读当前partition然后扩散到所有partition。

**Comment by liwenhui-soul** [comment]
> 参考Gemini的论文，[https://coolerzxw.github.io/data/publications/gemini_osdi16.pdf。spread的原意是读当前partition然后扩散到所有partition。](https://coolerzxw.github.io/data/publications/gemini_osdi16.pdf%E3%80%82spread%E7%9A%84%E5%8E%9F%E6%84%8F%E6%98%AF%E8%AF%BB%E5%BD%93%E5%89%8Dpartition%E7%84%B6%E5%90%8E%E6%89%A9%E6%95%A3%E5%88%B0%E6%89%80%E6%9C%89partition%E3%80%82)

`  auto bsp_send = [&](bsp_send_callback_t<mepa_ag_message_t<MSG>> send) {
    auto send_callback = [&](const mepa_ag_message_t<MSG>& message) {
      send(partitioner->get_partition_id(message.v_i_), message);
    };

    mepa_ag_context_t<MSG> context { send_callback };

    auto traversal = [&](vid_t v_i, const typename GRAPH::adj_unit_list_spec_t& adjs) {
      merge_task(context, v_i, adjs);
      return true;
    };

    size_t chunk_size = 256;
    while (graph.next_chunk(traversal, &chunk_size)) { }
  };`
你说的是spread_message这个函数，确实如你所说。但我指的是aggregate_message，这个在dualmodel里对应的是pull操作，我反复看了代码，貌似就是自己发给自己？

**Comment by ustcyu** [comment]
并不是自己发给自己。
图按照顶点ID被切分到不同机器，某顶点和邻居顶点通信时，需要根据邻居顶点ID判断该邻居在哪台机器，然后向该机器pull/push消息。

**Comment by xuguruogu** [comment]
是所有机器发消息给这个vid
