### ISSUE TITLE
请问水平扩展会受单机内存的限制吗？

### ISSUE THREAD

**Issue by zlcook** [Tencent/plato#67]
请问计算规模可以水平扩展吗？会受单机内存的限制吗？如果有限制，那么支持最大多少顶点和边呢？

**Comment by ustcyu** [comment]
请问水平扩展指的是单机还是集群？如果是集群就不受限于单机内存

**Comment by zlcook** [comment]
> 请问水平扩展指的是单机还是集群？如果是集群就不受限于单机内存

集群的水平扩展。[issue61](https://github.com/Tencent/plato/issues/61)中说最大顶点数受uint32_t的限制，也就最大顶点规模约43亿

**Comment by ustcyu** [comment]
顶点是32位，有最大值限制，但这个和单机内存无关，只是32位存储的限制
