### ISSUE TITLE
another MPI_ALLREDUCE error

### ISSUE THREAD

**Issue by patricxu** [Tencent/plato#68]
(graph) [root@gpudashujucbd010030 plato-master]# scripts/run_pagerank_local_ppd.sh
+++ dirname scripts/run_pagerank_local_ppd.sh
++ realpath scripts
+ CUR_DIR=/home/pld_xuqi/plato-master/scripts
++ realpath /home/pld_xuqi/plato-master/scripts/..
+ ROOT_DIR=/home/pld_xuqi/plato-master
+ cd /home/pld_xuqi/plato-master
+ MAIN=/home/pld_xuqi/plato-master/bazel-bin/example/pagerank
+ WNUM=4
+ WCORES=4
+ INPUT=/home/pld_xuqi/plato-master/data/calls_simple.csv
+ OUTPUT=/tmp/pagerank
+ IS_DIRECTED=true
+ EPS=0.0001
+ DAMPING=0.85
+ ITERATIONS=100
+ PARAMS+=' --threads 4'
+ PARAMS+=' --input /home/pld_xuqi/plato-master/data/calls_simple.csv --output /tmp/pagerank --is_directed=true'
+ PARAMS+=' --iterations 100 --eps 0.0001 --damping 0.85'
+ MPIRUN_CMD=/home/pld_xuqi/plato-master/3rd/mpich/bin/mpiexec.hydra
+ export LD_LIBRARY_PATH=:/home/pld_xuqi/plato-master/3rd/hadoop2/lib
+ LD_LIBRARY_PATH=:/home/pld_xuqi/plato-master/3rd/hadoop2/lib
+ mkdir -p /tmp/pagerank
+ /home/pld_xuqi/plato-master/3rd/mpich/bin/mpiexec.hydra -n 4 /home/pld_xuqi/plato-master/bazel-bin/example/pagerank --threads 4 --input /home/pld_xuqi/plato-master/data/calls_simple.csv --output /tmp/pagerank --is_directed=true --iterations 100 --eps 0.0001 --damping 0.85
I0316 17:43:56.151432 45720 base.hpp:179] thread support level provided by MPI:
I0316 17:43:56.151504 45720 base.hpp:182] MPI_THREAD_MULTIPLE
I0316 17:43:56.151517 45720 base.hpp:211] threads: 4
I0316 17:43:56.151523 45720 base.hpp:212] sockets: 2
I0316 17:43:56.151527 45720 base.hpp:213] partitions: 4
I0316 17:43:56.310217 45720 detail.hpp:106] partition-0, file-count: 1
I0316 17:43:56.310246 45720 detail.hpp:106] partition-1, file-count: 0
I0316 17:43:56.310251 45720 detail.hpp:106] partition-2, file-count: 0
I0316 17:43:56.310256 45720 detail.hpp:106] partition-3, file-count: 0
I0316 17:45:56.170219 45720 structure.hpp:496] edges:        315105018
I0316 17:45:56.170258 45720 structure.hpp:497] vertices:     69595666
I0316 17:45:56.170264 45720 structure.hpp:498] max_v_id:     1900430254
I0316 17:45:56.170267 45720 structure.hpp:499] is_directed_: 1
I0316 17:45:56.170274 45720 structure.hpp:501] load edges cache cost: 120.019s
I0316 17:46:35.161594 45720 structure.hpp:515] generate degrees cost: 38.991s
I0316 17:46:35.161670 45720 sequence.hpp:51] total_amount: 1985401002, alpha: 24
Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(907).......: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x7f1c02e6f010, count=1900430255, MPI_UNSIGNED, MPI_SUM, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(764).:
MPIR_Allreduce_intra(268):
MPIR_Bcast_impl(1452)....:
MPIR_Bcast(1476).........:
MPIR_Bcast_intra(1287)...:
MPIR_Bcast_binomial(250).: message sizes do not match across processes in the collective routine: Received -32766 but expected -988213572

**Comment by patricxu** [comment]
The max vertex id is 1,900,430,254 in this case. And I bypass the issue by mapping the ids to 0~69595665

**Comment by xuguruogu** [comment]
> The max vertex id is 1,900,430,254 in this case. And I bypass the issue by mapping the ids to 0~69595665

That's the correct way to use Plato.

**Comment by yanjianyu-nwpu** [comment]
I meet the error
2021-08-23T02:03:59.158633578Z stderr Fatal error in MPI_Allreduce: Other MPI error, error stack:
2021-08-23T02:03:59.158636361Z stderr MPI_Allreduce(907).......: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x7f02ffc84010, count=707652794, MPI_UNSIGNED, MPI_SUM, MPI_COMM_WORLD) failed
2021-08-23T02:03:59.158639434Z stderr MPIR_Allreduce_impl(764).: 
2021-08-23T02:03:59.158642079Z stderr MPIR_Allreduce_intra(268): 
2021-08-23T02:03:59.158644684Z stderr MPIR_Bcast_impl(1452)....: 
2021-08-23T02:03:59.158647154Z stderr MPIR_Bcast(1476).........: 
2021-08-23T02:03:59.15864998Z stderr MPIR_Bcast_intra(1287)...: 


There are 800000000 vertex in my data. the problem is the number of vertex?
