### ISSUE TITLE
关于源码的一些疑问

### ISSUE THREAD

**Issue by JingLiofLiJing** [Tencent/plato#69]
看源码的时候主要有两点不解：
       1. shuffle里面由于多线程的关系，所以最后额外再来一次probe_once()，我理解这样是因为多线程一起接受，同一个源计算节点发送过来的数据在写buffer还没完成时另一个线程接收到了finish signal，这样要额外再test一下，但是在某些情况下，finish_signal 接收完成时多于1个线程还在写buffer，这样额外只调用一次probe_once()会不会还是有可能漏了一部分数据（因为vector长度默认为3，可能会出现）？
       2. 我看了一下c++ reference，memcpy如果直接写一个类而非序列化的话应该是类得满足POD，即is_standard_layout 和 is_trival 都为true才行，代码中同时杂糅了两种不同的判断方法可能会有问题？

**Comment by xuguruogu** [comment]
http://www.cplusplus.com/reference/type_traits/is_standard_layout/

> struct B : A { int j; };

按照我对c++的内存结构的理解，struct B是可以memcpy进行序列化的，is_standard_layout<B>()为false。

**Comment by JingLiofLiJing** [comment]
https://en.cppreference.com/w/cpp/types/is_trivially_copyable中note提到

Objects of trivially-copyable types are the only C++ objects that may be safely copied with std::memcpy or serialized to/from binary files with std::ofstream::write()/std::ifstream::read().
In general, for any trivially copyable type T and an object obj1 of T, the underlying bytes of obj1 can be copied (e.g. by means of std::memcpy or std::memmove) into an array of char, unsigned char or std::byte or into obj2, a distinct object of T. Neither obj1 nor obj2 may be a potentially-overlapping subobject.
If the underlying bytes of obj1 is copied into such an array, and then the resulting content is copied back into obj1, obj1 will hold its original value. If the underlying bytes of obj1 are copied into obj2, obj2 will hold obj1's value.
所以改成std::is_trivially_copyable<T>::value就能满足了。

**Comment by xuguruogu** [comment]
> [https://en.cppreference.com/w/cpp/types/is_trivially_copyable中note提到](https://en.cppreference.com/w/cpp/types/is_trivially_copyable%E4%B8%ADnote%E6%8F%90%E5%88%B0)
> 
> Objects of trivially-copyable types are the only C++ objects that may be safely copied with std::memcpy or serialized to/from binary files with std::ofstream::write()/std::ifstream::read().
> In general, for any trivially copyable type T and an object obj1 of T, the underlying bytes of obj1 can be copied (e.g. by means of std::memcpy or std::memmove) into an array of char, unsigned char or std::byte or into obj2, a distinct object of T. Neither obj1 nor obj2 may be a potentially-overlapping subobject.
> If the underlying bytes of obj1 is copied into such an array, and then the resulting content is copied back into obj1, obj1 will hold its original value. If the underlying bytes of obj1 are copied into obj2, obj2 will hold obj1's value.
> 所以改成std::is_trivially_copyable::value就能满足了。

确实如此，使用std::is_trivially_copyable即可

**Comment by JingLiofLiJing** [comment]
关于第一个问题，会不会存在多于1组发送数据没缓存完的时候收到了所有的finish symbol，这样额外多一次probe_once()还是会造成数据接收不全，比如 1 2线程在接收最后两批数据，3号线程收到并提前检测到了最后两个finish symbol，这样的情况？

**Comment by skyssj** [comment]
针对问题一，并不会遗漏数据。
前提：
  1. 对于一个确定的发送端来说 finish_signal 一定是在所有“数据消息”都发送完毕后最后才发送；
  3. MPI 协议保证 P2P 的协议是按照顺序发送的。
基于以上 2 点，当接收端处理到最后一条  finish_signal  时，缓冲区中一定不会残留未被处理的“数据消息”。假设存在，那么这条消息的偏序顺序一定要晚于某一条  finish_signal ，这与前提1矛盾。

**Comment by JingLiofLiJing** [comment]
比如B机器现在开了4个线程接收，A和C节点给B节点发送shuffle数据，

> 针对问题一，并不会遗漏数据。
> 前提：
> 
> 1. 对于一个确定的发送端来说 finish_signal 一定是在所有“数据消息”都发送完毕后最后才发送；
> 2. MPI 协议保证 P2P 的协议是按照顺序发送的。
> 
> 基于以上 2 点，当接收端处理到最后一条 finish_signal 时，缓冲区中一定不会残留未被处理的“数据消息”。假设存在，那么这条消息的偏序顺序一定要晚于某一条 finish_signal ，这与前提1矛盾。

在non-blocking的语义下，假设A节点发1批数据后发finish symbol，B节点发1批数据发finish symbol，都是对C发的；C节点开了4个线程irecv，前两个节点按顺序先收到了A和B的数据，此时另两个线程收到了finish_symbol。Isend只要缓冲区的数据发送完了就会确认status，Irecv保证缓冲区收完了就会确认status，这样P2P的发送也满足有序的

A nonblocking send call indicates that the system may start copying data out of the send buffer. The sender should not modify any part of the send buffer after a nonblocking send operation is called, until the send completes.
A nonblocking receive call indicates that the system may start writing data into the receive buffer. The receiver should not access any part of the receive buffer after a nonblocking receive operation is called, until the receive completes.

**Comment by skyssj** [comment]
是的，您提的这种场景并没有造成数据接收不全呢，所有数据都被前2个线程处理了

**Comment by JingLiofLiJing** [comment]
> 是的，您提的这种场景并没有造成数据接收不全呢，所有数据都被前2个线程处理了

不会啊，代码中testany中检测到第三第四个线程接收完两个finish symbol就满足条件退出了，此时如果第一第二个还在写缓存，代码就直接关闭了requests

**Comment by skyssj** [comment]
您的意思是第一第二个还在读缓存的意思吧，所有接收线程都是在一个 omp 并行块中，最后会有一个隐含的 barrier，所以第一第二个线程读缓存的操作一定会被执行。

**Comment by JingLiofLiJing** [comment]
我理解的话这个barrier只是同步了所有线程会都调用非阻塞的Irecv方法就退出了block，Irecv调用后会立即返回而不是等待写完缓冲区，对接受数据的判断这个隐含的barrier没有起到任何作用，这一步只是为了调用Test_any的时候保证所有的request handles都是active的，不然flag和index会出现未定义行为，但是最后是强制cancel了所有的request，这是还是会有可能阻断比如说来自某个计算节点发送的大数据的接收。

**Comment by ustcyu** [comment]
已经解释了问题，关闭本issue，如有问题，请reopen。
