### ISSUE TITLE
Vs JanusGraph

### ISSUE THREAD

**Issue by tryhardest** [Tencent/plato#7]
Have you done any benchmarking against something as wide spread as Janus Graph? 

This looks exciting but I'm curious if it's worth a solid days commitment of time.

**Comment by ustcyu** [comment]
Plato(open-sourced version) and JanusGraph focus on different directions. Currently, Plato open sourced its ability on offline graph processing. However, JanusGraph is a graph database and focus on online graph analytics. So, it's hard to compare both systems. Plato will open source more on offline graph computing and online graph analytics in the future. Stay tuned.

**Comment by yzhwang** [comment]
We have noted this in our road map. However, as we do not have any immediate plan to cover graph database use case, will close this for now.

**Comment by patricxu** [comment]
@ustcyu What do you mean by "online/offline" ? OLTP == online and OLAP == offline?
