### ISSUE TITLE
多机并行时，如何给mpich指定ssh通讯端口？

### ISSUE THREAD

**Issue by sosofun** [Tencent/plato#70]
目前把plato 跑在k8s集群上，为了保证资源共享使用，容器直接通过mpi通讯时，我们会指定ssh的通讯端口，比如horovod任务默认用openmpi 可以通过参数指定ssh通讯20001端口：” -mca plm_rsh_args '-p 20001' “ ；我查了下mpich手册，看到通过"export MPIR_CVAR_CH3_PORT_RANGE=low:hi" 指定tcp通讯端口，并不能指定ssh端口。

请教如果用mpich 来满足这种需求呢？

**Comment by xuguruogu** [comment]
mpi通过默认的ssh进行通信控制，理应和部署Hadoop具有同样的要求。可以尝试修改/etc/ssh/sshd_config，或者试一下其他的ssh配置方式。

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
