### ISSUE TITLE
请问plato开源license是哪种？何时第一个版本发布？

### ISSUE THREAD

**Issue by nginxpre** [Tencent/plato#72]
目前没有看到plato的license申请，那么plato采用哪种license，在拷贝，商用上有什么样的限制？
另外我们打算何时发布第一个版本？

**Comment by xuguruogu** [comment]
Plato使用BSD license。https://github.com/Tencent/plato/blob/master/LICENSE。

> Terms of the BSD 3-Clause License: 
> --------------------------------------------------------------------
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of THL A29 Limited/the above copyright holders nor the names of their contributors may be used to endorse or promote products derived from this software without specific prior written permission.

你在使用、修改和分发时需要保留本license。
