### ISSUE TITLE
Could you prvide a demo to run plato on clusters?

### ISSUE THREAD

**Issue by patricxu** [Tencent/plato#73]

**Comment by xuguruogu** [comment]
plato use mpi as cluster runner. Please refer to [Running an MPI Cluster within a LAN](https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/)

**Comment by patricxu** [comment]
Finally I have gone through this issue! There are several key points we need to handle.
1. start the nfs service and put the exe and data to the nfs directory which can be accessed by all the nodes in the cluster.
2. make sure all the nodes are mutally sshable without password.
3. you might encounter a MPI_Send rejection error in which case you should modify the hostfile like this:
   node1-name (or IP): 2
   node2-name (or IP): 2
   ....
  

[http://repast.10935.n7.nabble.com/Repast-HPC-distribution-problem-td9724.html](http://repast.10935.n7.nabble.com/Repast-HPC-distribution-problem-td9724.html)
