### ISSUE TITLE
403 forbidden when trying to download dependencies

### ISSUE THREAD

**Issue by CoGore** [Tencent/plato#74]
I tried downloading dependencies as instructed.
`# download and build staticlly linked libraries.
./3rdtools.sh distclean && ./3rdtools.sh install`

But I came across an error like this:

~/plato/3rd ~/plato
~/plato
distclean 3rd done!
~/plato/.downloads ~/plato
--2020-03-30 01:19:42--  https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 52.41.180.114, 54.191.3.105
Connecting to dl.bintray.com (dl.bintray.com)|52.41.180.114|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-30 01:19:44 ERROR 403: Forbidden.

'wget -O boost_1_68_0.tar.gz https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz' exec failed with code 8, abort install process!

Is there anything I can do about it? Thanks.

**Comment by xuguruogu** [comment]
Please download boost source manually, and rename it to `.download/boost_1_68_0.tar.gz`. The detail of the install precess please refer to the shell script.
 https://github.com/Tencent/plato/blob/2230af32641f9ae290480d7a86bf053f019aa253/3rdtools.sh#L23-L31

If the file `boost_1_68_0.tar.gz` exist, download process will be skipped automaticly.

**Comment by ustcyu** [comment]
We will close this one for now. If anyone has any questions, please reopen and we are pleased to discuss more.
