### ISSUE TITLE
Heterogeneous graph

### ISSUE THREAD

**Issue by patricxu** [Tencent/plato#75]
Currently, the graph format is quite simple:
id1, id2 [,weight]

Will Plato be supporting the graph whose nodes (or edges) have more properties, or even more sophisticated graph e.g. the heterogeneous graph?

**Comment by patricxu** [comment]
any idea on this? @xuguruogu

**Comment by xuguruogu** [comment]
We suggest transform heterogeneous graph into isomorphic graph to prevent performance suffer.

**Comment by ustcyu** [comment]
We will close this one for now. If anyone has any questions, please reopen and we are pleased to discuss more.
