### ISSUE TITLE
bnc算法如何控制抽样的节点个数？

### ISSUE THREAD

**Issue by datian9966** [Tencent/plato#82]
请问一下
cnc算法有明确的抽样个数参数，bnc应该如何设置抽样的节点个数？
目前所给出的参数有些没看懂 跑一个比较大的图的时候 会跑很久很久也出不来结果
谢谢！

**Comment by xuguruogu** [comment]
--max_iteration表示抽样多少节点

**Comment by datian9966** [comment]
@xuguruogu 好的 谢谢您 我去尝试一下
