### ISSUE TITLE
请问即将开源的那些算法有时间表吗？

### ISSUE THREAD

**Issue by datian9966** [Tencent/plato#84]
作者大大们~
麻烦问一下，咱这些即将开源的算法有一个大概的时间表嘛？ 很期待
 Incoming:
Word2Vec, Line, GraphVite
GCN 相关

**Comment by ustcyu** [comment]
感谢关注Plato

**Comment by ustcyu** [comment]
感谢对Plato的关注，后面会开源，stay-tuned ！

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
