### ISSUE TITLE
几个文档中的疑问

### ISSUE THREAD

**Issue by cfangplus** [Tencent/plato#87]
plato introduction文档中有几个疑问，在此向社区提出，
1，node2vec是一种emb算法，据我所知randomwalk只是其中一个步骤，所以文档中为何有Node2Vec-Randomwalk的说法？难道只是实现了node2vec算法中随机游走这部分的逻辑？
2，据我所知，GraphVite是加拿大一个AI研究机构推出的一个emb产品/框架，所以文档中所述即将开源的算法中把GraphVite和LINE等emb算法放在一起，意思是GraphVite也是一种emb算法吗？
3，据我所知，像Spark GraphX这种分布式图计算框架是基于Spark完成，它是无法完成GCN等算法的，那么plato作为一个已经经受了大规模数据量考验的图计算框架，如果后续支持GCN等算法，是否底层引擎需要有大变动？或者我这样问，为了适配离线图计算和GCN算法，plato在引擎层有什么特殊设计？

**Comment by ustcyu** [comment]
Plato目前的开源版本实现了node2vec算法的walk部分，暂不包含word2vec部分。Plato的任何roadmap都有可能改变，目前关于Embedding和GNN的支持我们在持续开发中，在下一版本发布前会进行更新。

**Comment by cfangplus** [comment]
多谢~

**Comment by ustcyu** [comment]
关闭本issue，如有问题，请reopen。
