### ISSUE TITLE
在资源足够的情况下，如何合理有效的提升执行效率？

### ISSUE THREAD

**Issue by datian9966** [Tencent/plato#89]
作者您好~
麻烦请问一下，在集群资源足够的情况下应该如何合理的提高执行效率呢？
比如有5台机器，每台100G内存
在跑某个算法的时候，默认每台机器1个进程4个线程，但是此时发现每台机器还有大量的内存剩余

1.此时我应该增加每台机器上的进程数吗？比如每台机器上跑4个进程乃至更多的进程线程数不变，这样合理吗？
2.我应该更多的增加进程还是更多的增加线程对效率有帮助呢？

谢谢

**Comment by xuguruogu** [comment]
进程数越少越好

**Comment by ustcyu** [comment]
资源配置可参考：
https://github.com/Tencent/plato/blob/master/doc/Resources.md

**Comment by datian9966** [comment]
@xuguruogu @ustcyu 非常感谢二位
