### ISSUE TITLE
Do we need to add envionment variables manually after running 3rdtools.sh?

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#9]
After 3rd-party packages are installed, is it necessary to add envionment variables manually? The build stage of plato suffers from "undefined reference to" error.
![err](https://user-images.githubusercontent.com/16053879/69022564-9dd50200-09b3-11ea-9857-ccad47eb3991.png)

**Comment by skyssj** [comment]
No. Could you paste your build command?

**Comment by matricer** [comment]
The problem is caused by missing packages including zlib, zlib-devel, glibc-static, libstdc++-static, numactl-devel. The problem is now solved.
