### ISSUE TITLE
Word2Vec开源

### ISSUE THREAD

**Issue by fanqie-will** [Tencent/plato#94]
请问Word2Vec是否已完成，是否可以现在开源？

**Comment by fanqie-will** [comment]
@xuguruogu

**Comment by fanqie-will** [comment]
@ustcyu xuguruogu

**Comment by ustcyu** [comment]
感谢对Plato的关注，Word2Vec暂未开源，目前我们在持续开发Embedding和GNN算法，Roadmap在下一版本发布前会进行更新。

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。

**Comment by iosmers** [comment]
招不招Embedding方向的实习生呀，目前研一，能去试试吗

**Comment by iosmers** [comment]
招不招Embedding方向的实习生呀，目前研一，能去试试吗
