### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by xiuechen** [Tencent/plato#96]
1.环境安装问题：sudo ./docker/install-dependencies.sh

+ . /etc/os-release
./docker/install-dependencies.sh: line 5: /etc/os-release: No such file or directory

在centos 6.3 上运行的时候会报错，是否一定只能支持centos 7.0呢

2.这个图算法要跑在yarn集群的话，是否要求每个yarn 的nodemanager上都要按照1）去安装环境呢？还是只要driver节点安装了环境就可以呢？

3.看了下例子中的图数据。貌似只支持srcid,dstid这种图数据输入方式，对于更加复杂的带属性的异构图，怎么配置输入呢？

**Comment by ustcyu** [comment]
1.报错是因为缺少/etc/os-release文件，可以看下/etc目录下是否有其他命名的os标识文件；
2.如果选择了以docker方式运行的话，那么就都需要安装docker环境；
3.暂不支持属性图，异构图需要编码。

**Comment by xiuechen** [comment]
多谢已经解决这个问题了，centos6没有这个文件，所以修改了：
#. /etc/os-release
export ID=centos
这样就可以安装了


bazel在centos6上没有现成的bin，自己下载下来编译了一下，编译前安装了java8和gcc4.8.3环境，也顺利编译通过了。


但是在build.sh的时候报错：
Use --sandbox_debug to see verbose messages from the sandbox.
In file included from ./plato/engine/walk.hpp:45:0,
                 from plato/engine/test/walk.cc:22:
./plato/util/object_buffer.hpp: In member function 'bool plato::object_dfs_buffer_t<T, Enable>::next_chunk(Traversal&&, size_t*)':
./plato/util/object_buffer.hpp:1217:38: error: there are no arguments to '__glibc_unlikely' that depend on a template parameter, so a declaration of '__glibc_unlikely' must be available [-fpermissive]
       if (__glibc_unlikely(!is.good())) break;
                                      ^
./plato/util/object_buffer.hpp:1217:38: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
./plato/util/object_buffer.hpp: In member function 'bool plato::object_dfs_buffer_t<T, typename std::enable_if<std::is_trivial<_Tp>::value>::type>::next_chunk(Traversal&&, size_t*)':
./plato/util/object_buffer.hpp:1261:38: error: there are no arguments to '__glibc_unlikely' that depend on a template parameter, so a declaration of '__glibc_unlikely' must be available [-fpermissive]
       if (__glibc_unlikely(!is.good())) break;
                                      ^
In file included from ./plato/graph/state.hpp:53:0,
                 from ./plato/graph/graph.hpp:26,
                 from ./plato/engine/walk.hpp:48,
                 from plato/engine/test/walk.cc:22:
./plato/parallel/bsp.hpp: In function 'int plato::bsp(plato::bsp_buffer_t*, plato::bsp_send_task_t<MSG>, plato::bsp_opts_t)':
./plato/parallel/bsp.hpp:239:51: error: 'MADV_HUGEPAGE' was not declared in this scope
       madvise(buff, cache_size, MADV_SEQUENTIAL | MADV_HUGEPAGE);
                                                   ^
./plato/graph/state.hpp:177: confused by earlier errors, bailing out
INFO: Elapsed time: 86.965s, Critical Path: 86.65s

**Comment by xiuechen** [comment]
build example内容的时候报：
Use --sandbox_debug to see verbose messages from the sandbox.
plato/util/thread_local_object.cc: In function 'void* plato::thread_local_object_detail::get_local_object(int)':
plato/util/thread_local_object.cc:117:38: error: '__glibc_unlikely' was not declared in this scope
   if (__glibc_unlikely(!local_objs_p_)) {
                                      ^
plato/util/thread_local_object.cc:129:47: error: '__glibc_unlikely' was not declared in this scope
   if (__glibc_unlikely(!obj.local_obj_p_.get())) {
                                               ^

**Comment by ustcyu** [comment]
https://github.com/Tencent/plato/tree/master/docker目录下列出了所支持的os，不包括centos6

**Comment by ustcyu** [comment]
https://github.com/Tencent/plato/tree/master/docker
目录下列出了所支持的os，不包括centos6

**Comment by ustcyu** [comment]
长时间没有回复，关闭本issue，如有问题，请reopen。
